export const DIAGNOSTICS_LIST = [
    "Abcès de la cuisse",
    "Abcès de la jambe",
    "Abcès de la région fessière",
    "Abcès de l’hallux",
    "Abcès du bras",
    "Abcès du mollet",
    "Ablation de matériel",
    "Acromioplastie",
    "Amputation",
    "Amputation de doigt",
    "Amputation de la pulpe du 2ᵉ doigt",
    "Amputation de l’avant-pied",
    "Amputation pulpaire",
    "Amputation traumatique de la main",
    "Ankylose de la hanche",
    "Anse de seau",
    "Arrachement de la TTA",
    "Arrachement du LLE",
    "Arrachement du tendon d’Achille",
    "Arthrite de la cheville",
    "Arthrite de la hanche",
    "Arthrite de l’épaule",
    "Arthrite du coude",
    "Arthrite du poignet",
    "Arthrite septique du genou",
    "Arthrodèse de la cheville",
    "Arthrodèse de la sous-talienne",
    "Arthrodèse de l’hallux",
    "Arthrodèse du pouce",
    "Arthrodèse tibio-astragalienne",
    "Arthrolyse du coude",
    "Arthrolyse du genou",
    "Arthrolyse métacarpo-phalangienne",
    "Arthrolyse sous arthroscopie",
    "Arthrorise",
    "Arthroscopie de la cheville",
    "Arthroscopie de l’épaule",
    "Arthroscopie du coude",
    "Arthroscopie du genou",
    "Arthrose de la cheville",
    "Arthrose de la sous-talienne",
    "Arthrose du genou",
    "Arthrose du poignet",
    "Arthrose talo-naviculaire",
    "Arthrose tibio-astragalienne",
    "Biopsie d’une récidive tumorale",
    "Biopsie musculaire",
    "Biopsie synoviale",
    "Biopsie-exérèse de kyste plantaire",
    "Biopsie-exérèse d’un kyste",
    "Blocage méniscal",
    "Bunionette",
    "Bursite",
    "Cal vicieux de la palette humérale",
    "Cal vicieux du 5ᵉ métacarpien",
    "Cal vicieux du col fémoral",
    "Cal vicieux du fémur",
    "Cal vicieux du plateau tibial",
    "Cal vicieux du radius",
    "Canal carpien sous endoscopie",
    "Capsulite rétractile",
    "Carcinome épidermoïde",
    "Chondrome",
    "Chondrome de la main",
    "Chondrosarcome",
    "Clou Gamma",
    "Clou de jambe",
    "Collection du psoas",
    "Compression du nerf cubital au coude",
    "Conflit sous-acromial",
    "Corps étranger",
    "Covid-19",
    "Coxalgie",
    "Coxarthrose secondaire",
    "Coxite",
    "Cross finger",
    "Cubitus varus",
    "Dermo-hypodermite",
    "Dermo-hypodermite non nécrosante",
    "Descellement de PTH",
    "Descellement septique",
    "Doigt en boutonnière",
    "Doigt en col de cygne",
    "Doigt porte",
    "Doigt à ressaut",
    "Douleur fessière",
    "Dysplasie de la hanche",
    "Dysplasie fibreuse",
    "Dystrophie synoviale",
    "Dégénérescence mucoïde du LCA",
    "Délabrement cutané",
    "Dépose de PTH",
    "Désarticulation de hanche",
    "Désarticulation de la main",
    "Désarticulation du genou",
    "Désarticulation du poignet",
    "Désinsertion du tendon rotulien",
    "Déformation du pied",
    "Entorse du genou",
    "Entorse du ligament collatéral latéral du genou",
    "Entorse du ligament collatéral ulnaire",
    "Escarre",
    "Escarre talonnière",
    "Exostose",
    "Fasciite nécrosante",
    "Fibrome chondromyxoïde",
    "Fracture bi-malléolaire",
    "Fracture comminutive des os du tarse",
    "Fracture de Bennett",
    "Fracture de Galeazzi",
    "Fracture de Monteggia",
    "Fracture de P2",
    "Fracture de Pouteau-Colles",
    "Fracture de Rolando",
    "Fracture de Segond",
    "Fracture de la 4ᵉ métacarpe",
    "Fracture de la 5ᵉ métacarpe",
    "Fracture de la base du 5ᵉ métacarpien",
    "Fracture de la base du 5ᵉ métatarsien",
    "Fracture de la clavicule",
    "Fracture de la diaphyse fémorale",
    "Fracture de la diaphyse fémorale droite",
    "Fracture de la diaphyse fémorale gauche",
    "Fracture de la diaphyse humérale",
    "Fracture de la glène humérale",
    "Fracture de la jambe",
    "Fracture de la malléole externe",
    "Fracture de la malléole interne",
    "Fracture de la mandibule",
    "Fracture de la palette humérale",
    "Fracture de la pointe de la rotule",
    "Fracture de la rotule",
    "Fracture de la symphyse pubienne",
    "Fracture de la tête du 5ᵉ métacarpien",
    "Fracture de la tête humérale",
    "Fracture de la tête radiale",
    "Fracture de l’acromion",
    "Fracture de l’apophyse coracoïde",
    "Fracture de l’apophyse coronoïde",
    "Fracture de l’astragale",
    "Fracture de l’extrémité inférieure de l’humérus",
    "Fracture de l’extrémité inférieure du fémur",
    "Fracture de l’extrémité inférieure du radius",
    "Fracture de l’extrémité supérieure de l’humérus",
    "Fracture de l’extrémité supérieure du tibia",
    "Fracture de l’hallux",
    "Fracture de l’olécrane",
    "Fracture de l’omoplate",
    "Fracture de l’os pyramidal",
    "Fracture de l’épitrochlée",
    "Fracture de l’épaule",
    "Fracture des deux os de l’avant-bras",
    "Fracture des métatarses",
    "Fracture des os du tarse",
    "Fracture des phalanges des doigts",
    "Fracture des phalanges du pied",
    "Fracture des plateaux tibiaux",
    "Fracture du 4ᵉ métatarse",
    "Fracture du bassin",
    "Fracture du calcanéum",
    "Fracture du col chirurgical de l’humérus",
    "Fracture du col du 5ᵉ métacarpe",
    "Fracture du col fémoral",
    "Fracture du cotyle",
    "Fracture du cubitus",
    "Fracture du fémur",
    "Fracture du grand os",
    "Fracture du grand trochanter",
    "Fracture du massif des épines",
    "Fracture du péroné",
    "Fracture du pilon tibial",
    "Fracture du plateau tibial",
    "Fracture du poignet",
    "Fracture du rachis",
    "Fracture du radius",
    "Fracture du scaphoïde",
    "Fracture du talus",
    "Fracture du tibia",
    "Fracture du trapèze",
    "Fracture du triquetrum",
    "Fracture du trochiter",
    "Fracture du tubercule de Tillaux",
    "Fracture d’un métacarpe",
    "Fracture d’un métatarse",
    "Fracture d’une phalange",
    "Fracture d’une épine tibiale",
    "Fracture négligée de l’extrémité supérieure du fémur",
    "Fracture négligée du talus",
    "Fracture ouverte de la clavicule",
    "Fracture ouverte de la jambe",
    "Fracture ouverte de la main",
    "Fracture ouverte de l’avant-bras",
    "Fracture ouverte du coude",
    "Fracture ouverte du cubitus",
    "Fracture ouverte du pied",
    "Fracture pathologique",
    "Fracture pertrochantérienne",
    "Fracture péri-prothétique",
    "Fracture sous-trochantérienne",
    "Fracture sur matériel d’ostéosynthèse",
    "Fracture sur prothèse",
    "Fracture tri-malléolaire",
    "Fracture-luxation de la cheville",
    "Fracture-luxation de la hanche",
    "Fracture-luxation des métatarses",
    "Fracture-luxation gléno-humérale",
    "Fracture-luxation ouverte",
    "Fracture-luxation trans-scapho-rétrolunaire",
    "Fracture-luxation trans-scapho-trans-triquetro-rétrolunaire",
    "Fracture-luxation trans-triquetro-rétrolunaire",
    "Ganz (ostéotomie)",
    "Genu valgum",
    "Genu varum",
    "Gonarthrose",
    "Gonarthrose tricompartimentale",
    "Greffe cutanée",
    "Greffe nerveuse",
    "Griffe cubitale",
    "Hallux rigidus",
    "Hallux valgus",
    "Hygroma",
    "Hygroma du genou",
    "Hygroma infecté",
    "Hypodermite nécrosante",
    "Hématome de la cuisse",
    "Hématome du psoas",
    "Hémangiome synovial",
    "Hémopathie maligne",
    "Image ostéolytique",
    "Infection sur matériel d’ostéosynthèse",
    "Infection sur prothèse",
    "Instabilité de la cheville",
    "Instabilité rotulienne",
    "Inégalité de longueur des membres inférieurs",
    "Ischémie digitale",
    "Kyste",
    "Kyste anévrysmal",
    "Kyste de la patte d’oie",
    "Kyste du LCA",
    "Kyste du genou",
    "Kyste du pouce",
    "Kyste hydatique",
    "Kyste hydatique du fémur",
    "Kyste mucoïde",
    "Kyste méniscal",
    "Kyste osseux",
    "Kyste pilosébacé",
    "Kyste poplité",
    "Kyste synovial",
    "Ligamentoplastie du LCA",
    "Ligamentoplastie du LCL",
    "Ligamentoplastie du LCP",
    "Ligamentoplastie scapholunaire",
    "Lipome",
    "Liposarcome",
    "Luxation acromio-claviculaire",
    "Luxation carpo-métacarpienne",
    "Luxation de Chopart",
    "Luxation de Lisfranc",
    "Luxation de la cheville",
    "Luxation de la hanche",
    "Luxation de la rotule",
    "Luxation de la tête cubitale",
    "Luxation de l’épaule",
    "Luxation de l’épaule chez sujet âgé",
    "Luxation des tendons fibulaires",
    "Luxation du coude",
    "Luxation du genou",
    "Luxation du poignet",
    "Luxation du pouce",
    "Luxation inter-phalangienne de l’hallux",
    "Luxation métacarpo-phalangienne",
    "Luxation négligée de la hanche",
    "Luxation négligée de l’IPPH",
    "Luxation négligée de l’épaule",
    "Luxation négligée du coude",
    "Luxation péritalienne",
    "Luxation radio-ulnaire distale",
    "Luxation récidivante de l’épaule",
    "Luxation rétrolunaire du carpe",
    "Luxation sous-talienne",
    "Luxation sterno-claviculaire",
    "Luxation sur PTH",
    "Luxation talo-naviculaire",
    "Luxation trans-scapho-rétrolunaire",
    "Lymphome",
    "Lésion SLAP",
    "Lésion du LCA",
    "Lésion du LLE du genou",
    "Lésion méniscale",
    "Lésion négligée du tendon fléchisseur",
    "Lésion tendineuse",
    "Lésion vasculaire de l’artère poplitée post-traumatique",
    "Lésions ligamentaires complexes du genou",
    "Macrodactylie",
    "Maillet Finger",
    "Main de meunuisier",
    "Maladie de Buerger",
    "Maladie de Charcot-Marie-Tooth",
    "Maladie de Dupuytren",
    "Maladie de Freiberg",
    "Maladie de Haglund",
    "Maladie de Kienböck",
    "Maladie de Müller-Weiss",
    "Maladie exostosante",
    "Masse de la cheville",
    "Masse de la cuisse",
    "Masse de la racine de la cuisse",
    "Masse de l’avant-bras",
    "Masse de l’index",
    "Masse de l’épaule",
    "Masse du genou",
    "Mosaicoplastie",
    "Morsure de serpent",
    "Morsure d’animal",
    "Myélome multiple",
    "Mélanome talonnier droit",
    "Mélanome unguéal",
    "Méniscectomie",
    "Métastase osseuse",
    "Métatarsalgie",
    "Neurofibromatose",
    "Neurolyse du nerf médian",
    "Neurolyse-transposition du nerf ulnaire",
    "Névrome de Morton",
    "Névrome de la main",
    "Névrome du nerf radial",
    "Nécrose aseptique de la tête fémorale",
    "Nécrose aseptique du naviculaire",
    "Ongle incarné",
    "Orteil en griffe",
    "Ossifications hétérotopiques",
    "Ostéite chronique",
    "Ostéite de la jambe",
    "Ostéite du calcanéum",
    "Ostéo-arthropathie neurogène",
    "Ostéochondrite de la cheville",
    "Ostéochondrite du genou",
    "Ostéochondromatose de la cheville",
    "Ostéochondromatose du genou",
    "Ostéogenèse imparfaite",
    "Ostéome ostéoïde",
    "Ostéomyélite chronique",
    "Ostéonécrose aseptique de la tête fémorale",
    "Ostéonécrose de la tête fémorale",
    "Ostéotomie fémorale de valgisation",
    "Ostéotomie tibiale de valgisation",
    "PIH",
    "PTE",
    "PTG bilatérale",
    "PTG de reconstruction",
    "PTG massive",
    "PTGF",
    "PTH",
    "PTH double mobilité",
    "Panaris",
    "Parage",
    "Paralysie cubitale",
    "Paralysie du SPE",
    "Paralysie du nerf cubital",
    "Paralysie du nerf radial",
    "Paralysie du nerf sciatique",
    "Paralysie du plexus brachial",
    "Paralysie médio-cubitale",
    "Paralysie sciatique",
    "Perte de substance cutanée",
    "Perte de substance musculaire",
    "Phlegmon de la main",
    "Pied bot varus équin",
    "Pied creux varus",
    "Pied diabétique",
    "Pied neurologique",
    "Pied rhumatoïde",
    "Pied spastique",
    "Pied varus équin",
    "Plaie ancienne de la fesse",
    "Plaie ancienne de la main",
    "Plaie de la cheville",
    "Plaie de la cuisse",
    "Plaie de la hanche",
    "Plaie de la main",
    "Plaie de l’avant-bras",
    "Plaie du bras",
    "Plaie du coude",
    "Plaie du creux axillaire",
    "Plaie du genou",
    "Plaie du mollet",
    "Plaie du pied",
    "Plaie du poignet",
    "Plaie du pouce",
    "Plastie de l’ongle",
    "Poller screw",
    "Polydactylie",
    "Pouce à ressaut",
    "Protrusion acétabulaire",
    "Pseudarthrose de la clavicule",
    "Pseudarthrose de la malléole externe",
    "Pseudarthrose de la malléole interne",
    "Pseudarthrose de la rotule",
    "Pseudarthrose de l’astragale",
    "Pseudarthrose de l’humérus",
    "Pseudarthrose du cubitus",
    "Pseudarthrose du fémur",
    "Pseudarthrose du radius",
    "Pseudarthrose du scaphoïde",
    "Pseudarthrose du tibia",
    "Pubalgies",
    "Raideur des doigts",
    "Raideur du coude",
    "Raideur du genou",
    "Reconstruction du point d’angle postéro-latéral",
    "Reprise de PIH",
    "Reprise de PTH",
    "Reprise de ligamentoplastie du LCA",
    "Reprise de prothèse de Moore",
    "Reprise des tendons extenseurs de l’index",
    "Reprise d’arthrodèse de la cheville",
    "Rhumatisme psoriasique",
    "Rhizarthrose",
    "Ring finger",
    "Rupture de la coiffe des rotateurs",
    "Rupture de l’appareil extenseur",
    "Rupture du LCA",
    "Rupture du LCP",
    "Rupture du LLI",
    "Rupture du tendon d’Achille",
    "Rupture du tendon long extenseur du pouce",
    "Rupture du tendon quadricipital",
    "Rupture du tendon rotulien",
    "Rupture négligée d’un tendon extenseur",
    "Rupture négligée du tendon fléchisseur profond",
    "Rupture négligée du tendon long extenseur du pouce",
    "Réimplantation de la main",
    "Rétraction cutanée",
    "Sacro-iliite",
    "Sarcome des parties molles",
    "Scapulectomie totale",
    "Section du tendon extenseur",
    "Section du tendon fléchisseur",
    "Section du tendon long extenseur de l’hallux",
    "Section fléchisseur négligée",
    "Section tendineuse",
    "Spondylarthrite ankylosante",
    "Sub-amputation du poignet",
    "Suture méniscale",
    "Syndactylie de la main",
    "Syndrome de Volkmann",
    "Syndrome des loges",
    "Syndrome du canal carpien",
    "Syndrome du canal tarsien",
    "Syndrome du sinus du tarse",
    "Synostose radio-ulnaire",
    "Synovite du coude",
    "Synovite du genou",
    "Synovite non spécifique",
    "Synovite villo-nodulaire",
    "Tailor’s bunion",
    "Tendinite des péroniers",
    "Tendinopathie calcifiante de la coiffe",
    "Tendinopathie de la coiffe des rotateurs",
    "Tendinoscopie",
    "Traumatisme crânien",
    "Traumatisme de l’avant-pied",
    "Traumatisme pulpaire",
    "Traumatisme unguéal",
    "Triple arthrodèse de la cheville",
    "Tuberculose osseuse",
    "Tumeur cutanée",
    "Tumeur de la main",
    "Tumeur de la scapula",
    "Tumeur de l’aileron sacré",
    "Tumeur des parties molles",
    "Tumeur du bassin",
    "Tumeur du pied",
    "Tumeur du poumon",
    "Tumeur glomique",
    "Tumeur osseuse",
    "Tumeur vasculaire",
    "Tumeur à cellules géantes",
    "Tumeur à cellules géantes des gaines",
    "Tuméfaction de la cheville",
    "Tuméfaction du doigt",
    "Tuméfaction du mollet",
    "Ténolyse des fléchisseurs",
    "Ténosynovite",
    "Ténosynovite de De Quervain",
    "Ténosynovite du pied",
    "Ténotomie d’allongement du tendon d’Achille",
    "Ulcère cutané",
    "Vascularite",
    "Écrasement du membre",
    "Électrocution",
    "Épicondylite",
    "Épiphysiolyse de la tête fémorale",
    "Équivalent bimalléolaire",
    "Érysipèle"
];
