export const MOCK_KEYWORDS = [
    "Complication",
    "Cicatrice",
    "Chéloïde",
    "Dyschromique",
    "Hypertrophique",
    "Rétractile",
    "Désunion",
    "Hématome",
    "Infection",
    "Morel-Lavalée",
    "Nécrose",
    "Imagerie",
    "Panoramique Dentaire",
    "Face Basse",
    "Face Haute",
    "Hirtz",
    "Blondeau",
    "Téléradiographie",
    "Occlusal",
    "Rétro-alvéolaire",
    "Scanner",
    "IRM",
    "Traumatologie",
    "Balistique",
    "Accident De Travail",
    "Plaie",
    "Joue",
    "Sténon",
    "Nerf Facial",
    "Nez",
    "Paupière Supérieure",
    "Lèvre Supérieure",
    "Front",
    "Oreille",
    "Scalp",
    "Cou",
    "Fracture",
    "Mandibule",
    "Condyle",
    "Branche Montante",
    "Branche Horizontale",
    "Symphyse",
    "Perte De Substance",
    "Alvéolo-dentaire",
    "Ligature En Berceau",
    "Maxillaire",
    "Lefort",
    "Malaire",
    "Arcade Zygomatique",
    "Orbite",
    "Paroi Interne",
    "Toit D’orbite",
    "Plancher D’orbite",
    "Dystopie Canthale",
    "Canthopéxie",
    "CNEMFO",
    "Os Frontal",
    "Étage Antérieur",
    "Brèche Ostéoméningée",
    "Sinus",
    "Ostéosynthèse",
    "Plaque",
    "Fil D’acier",
    "Vis",
    "Fixateur Externe",
    "Blocage Intermaxillaire",
    "Distraction",
    "Greffe Osseuse",
    "Anatomie",
    "Lèvre Inférieure",
    "Paupières",
    "Techniques De Base",
    "Suture Simple",
    "Greffe De Peau",
    "Peau Mince",
    "Peau Totale",
    "Peau Amplifiée",
    "Crête Iliaque",
    "Pariétal",
    "Péroné",
    "Grand Dorsal",
    "Sein",
    "Sourcil",
    "Menton",
    "Peau",
    "Os",
    "Grand Pectoral",
    "Lambeau",
    "Libre",
    "Pédiculé",
    "Greffe Cartilagineuse",
    "Greffe Muqueuse",
    "Dysmorphose",
    "Béance Antérieure",
    "Étiologie",
    "Esthétique",
    "Lifting",
    "Lifting Cervico-jugal",
    "Plicature Du SMAS",
    "Lambeau De SMAS",
    "Platysmaplastie Antérieure",
    "Lifting Frontal",
    "Otoplastie",
    "Blépharoplastie Supérieure",
    "Blépharoplastie Inférieure",
    "Rhinoplastie",
    "Voie Externe",
    "Voie Endo-nasale",
    "Lipoaspiration",
    "Sous-mental",
    "Fistule",
    "Kyste",
    "Dermoïde",
    "Sébacé",
    "Mucoïde",
    "Tumeur",
    "Basocellulaire",
    "Sclérodermiforme",
    "Spinocellulaire",
    "Naevus",
    "Lipome",
    "Mélanome",
    "Carcinome Épidermoïde",
    "Cavité Buccale",
    "Mammoplastie",
    "Abdominoplastie",
    "Reconstruction",
    "Rhinopoïèse",
    "Face",
    "Membre Inférieur",
    "Membre Supérieur",
    "Tronc",
    "Récidive",
    "Adénome Pléomorphe",
    "Naevus De Jadassohn",
    "Adénopathie",
    "Parotide",
    "Rameau Mentonnier",
    "Paralysie Faciale",
    "Arme Blanche",
    "Webster",
    "Anophtalme",
    "Adénocarcinome",
    "Améloblastome",
    "Autre Tumeur Bénigne",
    "Autre Tumeur Maligne",
    "Gencive",
    "Tubérosité Maxillaire",
    "Muqueuse",
    "Lèvres",
    "Boule De Bichat",
    "Chinois",
    "Énophtalmie",
    "Exophtalmie",
    "Rééducation",
    "TS",
    "Radiothérapie",
    "Lobule",
    "3D",
    "Profil Massif Facial",
    "Lèvre Rouge",
    "Lèvre Blanche",
    "Congénital",
    "Plancher Buccal",
    "Ostéotomie",
    "Nerf Alvéolaire Inférieur",
    "Nerf Infra-orbitaire",
    "Extension Cutanée",
    "Fasciite Nécrosante",
    "Expansion Cutanée",
    "Histiocytofibrome",
    "LLL",
    "Dent",
    "Avulsion",
    "Lésions",
    "Escarre",
    "Angle",
    "Cellulite",
    "Glandes Salivaires",
    "Réduction Simple",
    "Traitement Fonctionnel",
    "Grand Fessier",
    "Décédé",
    "Pseudarthrose",
    "Cicatrisation Dirigée",
    "Cal Vicieux",
    "Ankylose",
    "Luxation",
    "Radius",
    "Col Du Fémur",
    "Prothèse De Moore",
    "Phalange",
    "Fémur",
    "Enclouage",
    "Verrouillage",
    "Tendon",
    "Extenseur",
    "Rotule",
    "Amputation",
    "Pilon Tibial",
    "Extrémité Inférieure Du Radius",
    "Malléole Externe",
    "Olécrane",
    "Jambe",
    "Diabète",
    "Fracture Sus Et Intercondylienne",
    "DCS",
    "Fracture Ancienne",
    "Suture Artérielle",
    "Suture Nerveuse",
    "Plaie De L’extenseur",
    "Ligamentoplastie De Slowe",
    "Fracture De La Jambe",
    "Subamputation De L’index",
    "Traumatisme De La Main",
    "Fracture Du Poignet",
    "Shees",
    "Fracture De L’humérus",
    "Fracture De L’extrémité Supérieure De L’humérus",
    "Bursite",
    "Ischémie",
    "Arrachement De L’épine Iliaque",
    "Démontage Du Matériel",
    "Paralysie Du Nerf Cubital",
    "Cunéenne Externe",
    "Poignet",
    "Cheville",
    "Astragale",
    "Fracture Ouverte",
    "Phlyctènes",
    "Fracture Luxation De La Cheville",
    "Plaie De La Hanche",
    "Fracture Bimalléolaire",
    "Luxation Acromio-claviculaire",
    "Écrasement Du Membre",
    "Fracture Du Pilon Tibial",
    "Fracture D’une Phalange",
    "Fracture Luxation Trans-scapho-rétrolunaire",
    "Scaphoïde",
    "Tête Radiale",
    "Base Du 5e Métatarsien",
    "Kapandji",
    "Tendon D’Achille",
    "Plaque Consolée",
    "Luxation Ouverte Du Coude",
    "Luxation Du Coude",
    "Fracture Sous-trochantérienne",
    "Plateau Tibial",
    "Tibia",
    "Vissage De La Tête Radiale",
    "Lésion Tendineuse",
    "Lésion Nerveuse",
    "Lésion Artérielle",
    "Fracture Du Cubitus",
    "Paralysie Du Nerf Médian",
    "Fracture Trimalleolaire",
    "Fracture Métacarpe",
    "Omoplate",
    "Nerf Radial",
    "Humérus",
    "Paralysie Du Nerf Radial",
    "Reprise",
    "Main",
    "Nécrose Cutanée",
    "Plaie Superficielle",
    "Prothèse",
    "Hanche",
    "Prothèse Cimentée",
    "Ostéoporose",
    "Vissage",
    "Ostéotomie",
    "Paresie Post-opératoire",
    "Paralysie Post-opératoire",
    "Ménisque",
    "Arthroscopie",
    "Luxation De Lisfranc",
    "Luxation Du Pied",
    "Lisfranc",
    "Traumatisme Violent",
    "Chute D’une Hauteur Élevée",
    "Décollement Épiphysaire",
    "Scaglietti",
    "Libération Musculaire",
    "Neurolyse",
    "Syndrome De Volkmann",
    "Avant-bras",
    "Libération Des Muscles",
    "Fr De La Malléole Interne",
    "Plaque Vissée",
    "Plaque Vissée",
    "Bennett",
    "Métacarpe",
    "Miniplaque",
    "Fr Des Deux Os Avant-bras",
    "Frac De L’extrémité Inférieure Du Radius",
    "Plaque En T",
    "Fracture De L’extrémité Inférieure Du Radius",
    "Voie Antérieure Radius",
    "Extrémité Inférieure Fémur",
    "Biopsie",
    "Pied",
    "Chopart",
    "Coxarthrose",
    "Boiterie",
    "PTH",
    "Fracture De Jambe Ouverte",
    "Ouverture Cutanée Stade 1",
    "Clou De Jambe",
    "Fracture Isolée Du Cubitus",
    "Pseudarthrose Du Cubitus",
    "Cal Vicieux Du Cubitus",
    "Arthrite Du Genou",
    "Douleur Du Genou",
    "Tuméfaction Du Genou",
    "Amputation De La Pulpe",
    "Fracture Ouverte Du Doigt",
    "Régularisation",
    "Plaie De L’avant-bras",
    "Cardiaque",
    "Mécanisme Supination Rotation Externe",
    "Trimalleolaire",
    "Genou",
    "Métastase",
    "Embrochage Haubanage",
    "Sus Et Intercondylienne",
    "DHS",
    "Prothèse Du Genou Tricompartimentale",
    "Arthrose Du Genou",
    "Ligamentoplastie",
    "Embrochage",
    "PTG",
    "Luxation Acromio-claviculaire",
    "Comminution",
    "Déficit De Prono-supination",
    "PIH",
    "Plaie Tendineuse Négligée",
    "Marginale Postérieure",
    "Monteggia",
    "Fracture Bifocale Cubitus",
    "Plaque 1/3 Tube Longue",
    "Fracture Ouverte De La Rotule",
    "Luxation Semilunaire",
    "Fracture De L’extrémité Supérieure De L’humérus",
    "Déformation Dos De Fourchette",
    "Luxation Épaule Antéro-interne",
    "Luxation Épaule Récidivante",
    "Suture Des Doigts",
    "Main De Menuisier",
    "Fracture Du Grand Trochantérien",
    "Pouteau-Colles",
    "Vis Spongieuse Directe",
    "Résection Scaphoïde + Arthrodèse Os Du Carpe",
    "Résection Du Scaphoïde + Arthrodèse Os Du Carpe",
    "Résection Du Scaphoïde",
    "Arthrodèse Des Os Du Carpe",
    "Fracture Sous-trochantérienne",
    "Transfusion",
    "Fracture Du Col Fémur",
    "Fracture Basicervicale Du Fémur",
    "Plaque DHS",
    "Sujet Âgé",
    "Fr Du Trochiter",
    "Traitement Orthopédique",
    "Plâtre Brachio-antébrachio-palmaire",
    "ECC Statique",
    "Verrouillage Distal Et Proximal",
    "Fracture Fermée",
    "Fracture De L’extrémité Inférieure Du Radius",
    "Fracture De La Jambe",
    "Paralysie Du SPE",
    "Tassement Du L1",
    "Plaque De Rochambeau",
    "Fr Cervico-trochantérienne",
    "Vis Malléolaire",
    "Fracture Du P2",
    "Fracture Articulaire Du P2",
    "Minivis",
    "Ouverture De La Syndesmose",
    "Maçon",
    "Chute D’un Échafaudage",
    "Arthrodèse De La Cheville",
    "Infection Post-opératoire",
    "Masse Au Niveau De La Cuisse",
    "Néo Du Sein",
    "Métastase",
    "Fracture Basicervicale",
    "Kyste Poplité",
    "Exérèse",
    "Kyste Synovial",
    "Tumeur Parties Molles",
    "Plaque DCP",
    "Ostéochondromatose Du Genou",
    "Blocage Du Genou",
    "Fracture Pertrochantérienne",
    "Pseudarthrose Du Scaphoïde",
    "Vissage Du Scaphoïde",
    "Greffe Du Scaphoïde",
    "Corps Étranger",
    "Rachis",
    "Hémangiome Caverneux",
    "Fracture De L’olécrane",
    "Fracture De L’apophyse Coronoïde",
    "Fracture Du Radius",
    "Fracture Bifocale Fémur",
    "Clou Gamma",
    "Fracture De La Rotule",
    "Fracture Sus Et Intercondylienne",
    "Fracture De La Malléole Externe",
    "Fracture À Trait Spiroïde De La Malléole Externe",
    "Luxation Récidivante De L’épaule",
    "Intervention De Latarjet",
    "Raideur Du Coude",
    "Fracture Glène Omoplate",
    "Luxation Centrale De La Tête Humérale",
    "Stade 4 Selon Goss-Edeberg",
    "Plaque En T Moulée",
    "Voie D’abord Postérieure Omoplate",
    "Fr Sus Et Intercondylienne",
    "Cal Osseux",
    "Moore",
    "Greffe Cutanée Inguinale",
    "Clou De Fémur",
    "Fracture De Fémur",
    "Clou Verrouillé",
    "Botte Plâtrée",
    "TTT Orthopédique",
    "Descellement Aséptique De PIH",
    "DCP",
    "Calcanéum",
    "Image Ostéolytique",
    "Extrémité Supérieure Tibia",
    "Drainage",
    "Kenneth-Jones",
    "Lésion Méniscale Opérée",
    "Rétraction Cutanée",
    "Libération",
    "Plastie",
    "Ouverture Cutanée Stade 2",
    "Vis De Syndesmose",
    "Paralysie Médio-cubitale",
    "Cécité",
    "Algodystrophie",
    "Ostéite",
    "Fracture Articulaire",
    "Trait De Refend Petit Trochanter",
    "Broche",
    "Fr Articulaire Radius",
    "Lésion Artère Humérale",
    "Fracture Styloïde Radiale",
    "ECM Humérus À Foyer Fermé",
    "Clou Dynamique",
    "Verrouillage Proximal",
    "Mac Gregor",
    "Hémodialyse",
    "AVP",
    "Nerf Cubital",
    "Transposition",
    "Ménisque Discoïde",
    "Ménisque Externe",
    "Scarf",
    "Hallux Valgus",
    "4e Doigt",
    "Bilateral",
    "TCG",
    "Tendon Long Fléchisseur Du Pouce",
    "Plaie Zone T2",
    "Plaie Commissurale",
    "Lésion Nerf Collatéral Palmaire Interne",
    "Péroné",
    "Enceinte",
    "Embrochage Pi",
    "Zone 2",
    "Fr Complexe Palette",
    "Fr De L’olécrane",
    "Fr Olécrane",
    "Fr Tête Radiale",
    "Ouverture Stade 3 CD",
    "Parage",
    "Fr P3",
    "Décollement Épiphysaire Stade 2 Extrémité Inférieure Fémur",
    "Fr Extrémité Inférieure Des Deux Os Avant-bras",
    "Broche Centro-médullaire",
    "Réduction",
    "Plâtre",
    "Greffe Cortico-spongieuse",
    "Crête Iliaque",
    "Matti-Russe",
    "Cortico-spongieuse",
    "Arcade De Frosch",
    "Coude",
    "EMG",
    "Nerf Interosseux",
    "Arcade Du Court Supinateur",
    "Plaque Vissée",
    "Fr Malléole Externe",
    "Paralysie Motrice Nerfs Radial Médian Et Cubital",
    "Ouverture Ponctiforme Coude",
    "Malléole Interne",
    "Arrachement Tendon Achille",
    "Arcade De Frohse",
    "Pseudarthrose Septique Jambe",
    "Fixateur Externe Jambe",
    "Sepsie Sur Matériel",
    "Cholécystectomisé",
    "Voie De Triquet",
    "Résection Tête Radiale",
    "Lymphœdème",
    "Tumeur À Cellules Géantes",
    "Image Ostéolytique",
    "Ciment Acrylique",
    "Sd Canal Carpien",
    "Garden 4",
    "Trouble Psychique",
    "Vissage Du Col",
    "Première Phalange",
    "3e Doigt",
    "Verrouillage Distal",
    "Traumatisme Lombaire",
    "Fracture De L4",
    "Fracture Calcanéum",
    "Angle De Böhler Positif",
    "3 Vis",
    "Fracture Non Déplacée",
    "Ostéoporose",
    "Vis De Herbert",
    "Arthrite De La Cheville",
    "Parage",
    "Problème Neurologique Névro-se",
    "Opéré Pour Fracture Des Deux Os Avant-bras",
    "Fr Basicervicale Col Fémoral",
    "Stade III",
    "Vis Spongieuse",
    "Vis Articulaire",
    "Stade II Salter Et Harris",
    "Cubitus",
    "Points Trans-osseux",
    "Cerclage Fil D’acier",
    "Cerclage",
    "Acier",
    "Désinsertion Rond Pronateur",
    "Plaque LCD Fracture Lombaire",
    "Fistule Cutanée",
    "Esslein",
    "Polytraumatisme",
    "Traumatisme Bifocal",
    "Traumatisme Crânien",
    "Fracture Jambe",
    "Enclouage",
    "Verrouillage Statique",
    "Plateau Tibial Externe",
    "Séparation Enfoncement",
    "TDM",
    "Piéton",
    "Vitaminothérapie",
    "Fracture Humérus",
    "Branche Motrice Nerf Radial",
    "Coude Flottant",
    "Fermée",
    "Diabétique",
    "Hypertendu",
    "ADO",
    "Accident De Sport",
    "Inversion",
    "Voie D’abord Antérieure Radius",
    "Problème Pulmonaire",
    "Allergie",
    "Canal Carpien",
    "Zone 1 Face Dorsale Pouce",
    "Kyste Pouce",
    "Paralysie Cubitale",
    "Sensitivo-motrice",
    "Paralysie Nerf Médian Sensitive",
    "Plaie Arme Blanche",
    "Griffe Cubitale",
    "Lasso",
    "Coup De Bâton",
    "Plaie Main",
    "Arthrodèse IPP",
    "Plastie Snow",
    "Nécrose Doigt",
    "Section Nerf Médian",
    "Section Tendon Extenseur 5e Doigt",
    "Fracture P1",
    "Zone 5",
    "Broche Centromédullaire",
    "Syndactilisation",
    "Grossesse",
    "Vissage Percutané Scaphoïde",
    "Fracture Non Déplacée Scaphoïde",
    "Chute",
    "Type IV Sernberg",
    "Anneau De Kerboul",
    "PTH Double Mobilité",
    "Dysplasie Hanche",
    "Fracture Épitrochlée",
    "Fractures Métacarpes",
    "Dysplasie",
    "Poliomyélite",
    "Tumeur Parties Molles",
    "Fracture Deux Os Avant-bras",
    "Morsure Cheval",
    "SAT",
    "VAT",
    "VAR",
    "Ouverture Ponctiforme",
    "Morsure Cheval",
    "Polyarthrite Rhumatoïde",
    "Corticoïde",
    "Os Pathologique",
    "Adénocarcinome Pulmonaire",
    "Métastase Osseuse",
    "Nerf Médian",
    "Nerf Cubital",
    "Paralysie Médio-cubitale",
    "Greffe Tendineuse",
    "Brûlure",
    "Macrodactylie",
    "2e Orteil",
    "Malformation",
    "Déformation",
    "Clou Gamma Court",
    "Fracture Sus Et Intercondylienne Fémur",
    "Plaque Cuillère",
    "Maçon",
    "Fracture Deux Os Avant-bras",
    "Fracture Tête Radiale",
    "Fracture Comminutive Tête Radiale",
    "Fr Col Fémoral",
    "Stade II Garden",
    "Hémodialysé Chronique",
    "TDM Hanche",
    "Voie D’abord Moore",
    "Ablation Matériel",
    "Inégalité Membres",
    "Gonarthrose",
    "Tiers Inférieur Tibia",
    "Plaque En Trèfle",
    "Genu Valgum",
    "Luxation Trans-triquétro-rétro-lunaire",
    "Embrochage Scapho-lunaire",
    "Embrochage Triquétra-lunaire",
    "Avant-bras Flottant",
    "Fracture 1/4 Externe Clavicule",
    "Fracture Styloïde 5e Métatarsien",
    "Hygroma",
    "AVC",
    "Traumatisme Ancien Genou",
    "Pus",
    "Luxation Épaule Sujet Âgé",
    "1er Épisode",
    "Récidivante",
    "Immobilisation",
    "Rééducation",
    "Problème Anesthésie + Bradycardie",
    "Arrachement TTA",
    "Laçage",
    "Immobilisation 2 Semaines",
    "Post-traumatique",
    "Kessler",
    "Fr Extrémité Inférieure Radius Articulaire",
    "Fracture Tiers Inférieur Jambe",
    "Plaque Cuillère",
    "Fracture Malléole Externe",
    "Fracture M4",
    "Diaphysaire",
    "Main Boxeur",
    "Lésion Ménisque Interne",
    "Arthroscopie",
    "Résection Méniscale",
    "Fistule Cutanée",
    "Ostéomyélite Chronique",
    "Bourgeonnement Cutané",
    "Ostéomyélite Chronique",
    "SPA",
    "Nerf Cubital",
    "Artère Cubitale",
    "Tendons Fléchisseur Superficiel Et Profond",
    "Petit Palmaire",
    "2e Orteil",
    "Fracture Bicondylienne",
    "Fracture Comminutive Fémur",
    "Plaque Fémur",
    "HTA",
    "Table Orthopédique",
    "Enfouissement",
    "Branche Digitale Nerf Radial Pouce",
    "Désarticulation Cheville",
    "Moto",
    "Arrêt Cardiaque",
    "Réanimation",
    "Embrochage Hackethal",
    "Pseudarthrose Jambe",
    "Décortication Ostéo-musculaire Judet",
    "Greffe Osseuse Crête Iliaque",
    "Rupture Négligée Tendon Long Extenseur Pouce",
    "Trisomie",
    "Fracture Métatarses",
    "Clou Humérus",
    "Pas De Paralysie Radiale",
    "Pseudarthrose Hypertrophique",
    "Pseudarthrose Fémur",
    "Vis Cassée",
    "Plaque Demi-tube",
    "Fracture Acromion",
    "Luxation Hanche Négligée",
    "Fracture Cotyle Ancienne",
    "Fracture Comminutive Calcanéum",
    "Angle De Böhler Négatif",
    "Embrochage Percutané Calcanéum",
    "Fracture Ouverte Stade 3 Avant-bras",
    "Morsure Âne",
    "Section Tendon Long Fléchisseur Pouce",
    "Section Branche Sensitive N. Médian Pouce",
    "DAC",
    "Phlegmon Main + Avant-bras",
    "Diabétique",
    "Insuline",
    "Insulinothérapie",
    "Syndrome Canal Carpien Bilatéral",
    "Prothèse Intermédiaire Tige Longue",
    "Fracture Sur Matériel",
    "Lame Plaque",
    "Luxation Métacarpo-phalangienne Pouce",
    "Colonne Pouce",
    "Délabrement Avant-bras",
    "Pontage Artère Humérale",
    "Section Nerf Médian",
    "Mise À Nu Os",
    "Résection Tumeur",
    "Perte Substance Tendineuse",
    "Fracture Clavicule",
    "1/3 Moyen",
    "Bandage En 8",
    "Décédé",
    "Embrochage Kapandji",
    "Déplacement Tête Antéro-interne",
    "Néo Sein",
    "Carcinome Canalaire Infiltrant",
    "Fracture Os Pathologique",
    "Fracture Col Sur Métastase",
    "Arthrodèse Capito-lunatum",
    "Clou Non Verrouillé",
    "Plaque Vissée Lecestre",
    "Fracture Plateau Tibial Externe",
    "Fr Diaphyse M1 Pouce",
    "Fr P1 Index",
    "Fr Comminutive",
    "Main De Toupie",
    "Menuisier",
    "Ouverture Cutanée",
    "Stade II Cauchoix-Duparc",
    "Fr Plateau Tibial Externe",
    "Enfoncement Séparation",
    "Greffe",
    "Amputation Bras",
    "Résection Scaphoïde",
    "Arthrodèse Lunato-capitatum",
    "Nécrose Pôle Proximal Scaphoïde",
    "AMO",
    "Fracture Col 5e Métacarpe",
    "Embrochage 5e Métacarpe",
    "Maladie De Dupuytren",
    "Dupuytren",
    "Aponévrectomie",
    "Clou Gamma Long",
    "Arrachement LLE",
    "Laxité Genou",
    "Chute Poignet Hyperextension",
    "Poignet Déformé",
    "Embrochage Type Py",
    "Embrochage Py",
    "Hémarthrose",
    "Schwannome",
    "Vis Malléolaire + Vis Syndesmose",
    "Entorse Cheville",
    "Fracture Col Péroné",
    "Chute Hauteur",
    "Piéton Heurté Moto",
    "Mécanisme Abduction + Pronation",
    "Mason 3",
    "Type 3 Classification Merle D’Aubigné",
    "Marginale Antérieure",
    "Agression",
    "Statique",
    "Amputation Post-traumatique",
    "Amputation Transfémorale",
    "Orchidectomie Droite",
    "Traumatisme OGE",
    "Fr 4e Métacarpe",
    "Fr Médiodiaphysaire 4e Métacarpe",
    "Plaie Thoracique",
    "Plaie Épaule",
    "Fr Acromion",
    "Fracture Cubitus",
    "Fr Comminutive Extrémité Inf Radius",
    "Embrochage Ulnoradial Palmaire",
    "Fr P1 5e Doigt",
    "Section Tendineuse",
    "Section Tendon Extenseur 5e Doigt",
    "Fr P1 Index",
    "Chute Escalier",
    "Luxation Lisfranc",
    "Luxation Spatulaire Latérale",
    "Chute Échafaudage",
    "Opéré Pour Fracture Tibia + Fémur",
    "Luxation Rétro-scapho-lunaire",
    "Ouvrier",
    "Luxation Trans-rétro-scapho-lunaire",
    "Kyste Doigt",
    "Masse Base 4e Doigt",
    "Médecin",
    "Kyste Gaine Fléchisseurs",
    "Masse Cuisse",
    "Ongle Incarné",
    "Ménisque Interne",
    "Corne Postérieure",
    "Calcification Tendon Achille",
    "Masse Doigt",
    "Biopsie Exérèse",
    "Tumeur Doigt",
    "Manœuvre Thompson Positive",
    "Rupture Négligée Tendon Achille",
    "Dépression Tendon Achille",
    "Ostéotomie Réorientation Radius",
    "Pseudarthrose Radius",
    "Femme De Ménage",
    "Débris Matériel Ostéosynthèse",
    "Tuberculose",
    "Arthrite Septique Genou",
    "Transposition TTA",
    "Instabilité Rotulienne",
    "Médialisation Vaste Médial",
    "Arthrose Fémoro-patellaire",
    "Masse Cuisse",
    "Masse Ulcérée Bourgeonnante",
    "Cal Vicieux Radius",
    "Limitation Prono-supination",
    "Angulation",
    "Fracture Base 5e Métacarpe",
    "Fracture Extra-articulaire Base",
    "Fracture Bilatérale Calcanéum",
    "Tentative Suicide",
    "Troubles Psychiques",
    "Traumatisme Rachidien",
    "Corps Étranger Intra-articulaire",
    "Syndrome Fémoro-patellaire",
    "Luxation Rotule",
    "Enclavement Clou",
    "Section Tendon Fléchisseur 5e Doigt",
    "IRC Stade Hémodialyse",
    "IHC",
    "Cardiopathie",
    "Accident domestique",
    "Vis de syndesmose",
    "Fracture aile iliaque",
    "Ménisque",
    "Instituteur",
    "Motocycliste",
    "Musicienne",
    "Liposarcome",
    "Abcès de la cuisse",
    "Nécrose aseptique du naviculaire",
    "Traumatisme du pied",
    "Arthrodèse",
    "Agrafe",
    "Fracture articulaire EIR",
    "Fracture métacarpienne",
    "Fracture pointe styloïde cubitale",
    "Fracture P1",
    "Subsaharien",
    "LMNH",
    "Radio-chimiothérapie",
    "Cuisse",
    "Plaie avant-bras",
    "Fracture du cotyle",
    "Paroi postérieure",
    "Fracture marginale antérieure",
    "Traumatisme unguéal",
    "Suture",
    "Instabilité antérieure chronique épaule",
    "Darach",
    "Luxation tête cubitale",
    "Handicap mental",
    "Adduction supination",
    "Fracture de la base du P1",
    "Fracture de la malléole interne",
    "Fracture du col de l’omoplate",
    "Fracture de l’omoplate",
    "Écharpe coude au corps",
    "Arthrite genou",
    "M4",
    "Luxation prothèse hanche",
    "Tendon extenseur",
    "D3 D4",
    "Traumatisme de la hanche",
    "Pacemaker",
    "Triquetrum",
    "Rupture de la plaque",
    "Mécanisme rotation externe supination",
    "Pipkin 3",
    "Synovectomie",
    "Plaie de la face dorsale du poignet",
    "Ostéophytes",
    "PTH double mobilité",
    "Voie de Harding",
    "Ligamentoplastie LCA",
    "Asthme",
    "Équivalent malléolaire interne",
    "Fracture tibia",
    "3",
    "Rupture partielle du fléchisseur du pouce",
    "Section nerf collatéral latéral palmaire du pouce",
    "Ostéite de la base de M1",
    "Fracture du 1/4 inférieur du tibia",
    "Extenseur",
    "Fracture du radius",
    "Friberg",
    "Fracture du plateau tibial interne",
    "Vissage percutané",
    "Fracture du plateau tibial interne",
    "TM avant-bras",
    "Gag",
    "Raccourcissement",
    "Ostéonécrose aseptique de la tête fémorale",
    "Luxation inférieure épaule",
    "Traumatisme pulpaire",
    "Main de menuisier",
    "Échafaudage",
    "Tendons fléchisseurs",
    "Lésion de la bandelette terminale",
    "Palette humérale",
    "Tendon d’Achille",
    "Fracture bifocale de la jambe",
    "Tumeur creux axillaire",
    "Épaule",
    "Lésion vasculo-nerveuse",
    "Stade 3C de Gustilo",
    "Plaie articulaire",
    "Plaie zone 2",
    "Plaie fléchisseur",
    "Fracture du bassin",
    "Réduction",
    "Fracture ouverte du P3",
    "Décollément de l’angle",
    "Fracture ouverte du P2",
    "Luxation columno-spatulaire",
    "Rachis",
    "Avant-pied",
    "Plaie ancienne de la main",
    "Bride de D2 et D3",
    "Section du tendon fléchisseur profond du D2",
    "Vissage percutané du plateau tibial interne",
    "Vissage percutané de la fracture du plateau tibial",
    "Vissage percutané du plateau tibial",
    "Embrochage type ISLAN",
    "Luxation épisodique de la rotule",
    "Plastie du vaste médial",
    "Nerf sciatique",
    "Grand sciatique",
    "Pied plat",
    "Valgus",
    "Valgus de l’arrière-pied",
    "Fracture du calcanéum",
    "Fracture de l’apophyse transverse de L5",
    "Fracture des os du tarse",
    "Recul de vis DHS",
    "Fracture 5ème métacarpien",
    "Coup de sabot d’un melet",
    "Section de la bandelette latérale du tendon extenseur",
    "Section du tendon petit palmaire",
    "Cotyle dysplasique",
    "Fracture trochantéro-diaphysaire",
    "Fracture col humérus",
    "Schizophrénie",
    "Fracture inter-ligamentaire",
    "Lésion négligée",
    "Vis cervicale 90",
    "Anse de seau",
    "Fracture cervico-trochantero-diaphysaire",
    "1/4 inférieur de la jambe",
    "Fracture comminutive",
    "Incarcération du vaste externe",
    "Ossification",
    "Stade 1 du Cauchoix et Duparc",
    "Embolie graisseuse",
    "Paralysie radiale",
    "Marche en canard",
    "Arthrose",
    "Lésion tendon rotulien",
    "Lésion de l’appareil extenseur",
    "Tendon rotulien",
    "Plâtre cruro-pédieux",
    "Fracture sus-ligamentaire",
    "Fracture du tubercule de Tillaux",
    "Décortication ostéomusculaire de Judet",
    "Fracture 1/4 inférieur tibia",
    "Coup de sabre",
    "Thrombophlébite",
    "PTH difficile",
    "Cal vicieux en varus",
    "Cadrage",
    "Fracture base 5ème métacarpien",
    "Fracture bicolonne",
    "Traction transtibiale",
    "Luxation sous-talienne",
    "Plâtre BABP",
    "Luxation négligée du coude",
    "Luxation postéro-externe du coude",
    "JBBira",
    "Plastie en VY du tendon triceps",
    "Suture méniscale",
    "Désinsertion méniscale",
    "RGd",
    "Fracture du col de l’humérus",
    "Amputation de la main",
    "Reflux gastro-duodénal",
    "AEG",
    "Voie dorsale",
    "Biopsie osseuse",
    "Nécrosectomie",
    "Col chirurgical de l’humérus",
    "Fracture du cotyle",
    "Fracture de Galeazzi",
    "Fracture transverse du cotyle",
    "Leiomyome vasculaire",
    "Nécrose aseptique",
    "Nécrose aseptique tête fémorale",
    "Allergique à l’aspirine",
    "Embrochage styloïdien",
    "Fracture de la tête cubitale",
    "Réduction sous sédation",
    "Fracture Pouteau-Colles",
    "Fracture du trochiter",
    "Verrouillage statique",
    "Traumatisme du genou",
    "Luxation PTH",
    "Écollement épiphysaire EIR",
    "Pneumothorax",
    "Analgesie post-opératoire",
    "Bloc axillaire",
    "Fracture comminutive de l’extrémité inférieure du radius",
    "Fracture cunéenne externe",
    "Écharpe coude au corps",
    "Fracture hémitransverse et de la paroi postérieure",
    "Fracture mandibule",
    "Manœuvre de Bohler",
    "LAMBEAU fascio-cutané à pédicule distal",
    "Cross-leg",
    "Tabagique",
    "Hémorroïdes",
    "Cannabis",
    "Niveau socio-économique moyen",
    "Vis de syndesmose",
    "Alcool",
    "Appuis précoces",
    "Marche",
    "Corticothérapie au long cours",
    "Désarticulation du genou",
    "Plaie musculaire",
    "Fracture styloïde cubitale",
    "Luxation antérieure du pied",
    "Fracture ouverte de la cheville",
    "Broche cruro-talienne",
    "Luxation rétro-lunaire",
    "Plaie du poignet",
    "Fracture du triquetrum",
    "Fracture du pisiforme",
    "Plaque 1/3 tube",
    "Main de boxeur",
    "Sportif",
    "Enfant",
    "Cartilage de croissance",
    "Sutures esthétiques",
    "Fracture marginale antérieure du tibia",
    "Sans domicile fixe",
    "Fracture de la palette humérale",
    "Hypoacousie",
    "Fracture du plateau tibial externe",
    "Maladie de Basedow",
    "Tumeur osseuse",
    "Tendon fléchisseur",
    "Hypertrophie du membre",
    "Orteil en griffe",
    "Plaque en crochet",
    "Fracture du côte",
    "Traumatisme thoracique",
    "Vis canulé",
    "Lésion du ménisque externe",
    "Fracture de l’apophyse coracoïde",
    "Artère radiale",
    "Nerf médian",
    "Fracture ouverte P1 hallux",
    "Accident hémorragique aux anticoagulants",
    "Fracture de l’astragale",
    "Fracture M1 pouce ouverte",
    "Fracture ouverte de MI",
    "Amputation de la cuisse",
    "Fibromateuse bénigne de type desmoïde",
    "Coxarthrose primitive",
    "Travailleur manuel",
    "Fracture de l’extrémité inférieure du fémur",
    "Choc rotulien",
    "Déplacement en recurvatum",
    "Fracture supra-condylienne de l’extrémité inférieure du fémur",
    "Ostéosynthèse percutanée",
    "Luxation bilatérale de l’épaule",
    "Crise convulsive",
    "Artère humérale",
    "Hématurie",
    "Plavix",
    "Prothèse intermédiaire de la hanche (PIH)",
    "Vascularite",
    "Ischémie",
    "Pathologie psychiatrique",
    "Traction bicondylienne",
    "Plaie artérielle",
    "Section de l’artère cubitale",
    "Fracture de P1 de l’hallux",
    "Hallux",
    "Plaie coude",
    "Pseudarthrose humérus",
    "Tendon fléchisseur",
    "5ème doigt",
    "1/4 inférieur du cubitus",
    "Kyste osseux",
    "Ostéome ostéoïde",
    "Anémie",
    "Plaie creux axillaire",
    "Séction artère axillaire",
    "Paralysie du nerf ulnaire, médian et radial",
    "Pseudarthrose humérus",
    "Plexus brachial",
    "Plaie vasculaire",
    "Fracture négligée",
    "Foyer fermé",
    "Nidus",
    "Calmé par l’aspirine",
    "La face antérieure de l’extrémité inférieure du radius",
    "Plaie du creux axillaire",
    "Hématome",
    "Artère axillaire",
    "Section de l’artère axillaire",
    "Épiphysiolyse",
    "Pied diabétique",
    "Amputation transtibiale",
    "Bosworth",
    "Fracture du trou obturateur",
    "Fracture de l’aileron sacré",
    "Luxation columno-spatulaire divergente",
    "Luxation MTP",
    "Luxation négligée de l’IPP",
    "Hyperextension du doigt",
    "Section du long fléchisseur du pouce",
    "Luxation transcapho-perilunaire",
    "Déplacement antérieur",
    "Luxation ouverte du poignet",
    "Hyperextension du poignet",
    "Manchette plâtrée",
    "Semi-lunaire en DISI",
    "Fracture du col du 5ème métacarpien",
    "Attelle intrinsèque plus",
    "Chondrome",
    "Fracture de la première phalange de l’hallux",
    "Ostéosynthèse percutanée",
    "Choc direct",
    "Fracture ouverte stade 2",
    "Hygroma infecté",
    "Fracture des métatarsiens 2ème et 3ème",
    "Plaie de l’appareil extenseur du genou",
    "Quadriceps",
    "Pseudarthrose du 4ème métacarpien",
    "Fracture de la base de la 3ème phalange du 3D",
    "Ostéomyélite chronique",
    "Embrochage antérieur",
    "Dermo-hypodermite",
    "Déplacement de l’EIR en postéro-interne",
    "Embrochage en va-et-vient",
    "Traumatisme ouvert avant-pied",
    "Section tendon extenseur",
    "Fracture trapèze",
    "Fracture trapézoïde",
    "Luxation trapézo-trapézienne",
    "Fracture-luxation de la tête du 3ème métacarpien",
    "Fracture premier métacarpien",
    "Fracture de l’extrémité inférieure du radius",
    "Délabrement face dorsale de la main",
    "Délabrement de la loge thénarienne",
    "Délabrement de la face dorsale du poignet",
    "Fracture spiroïde",
    "Lipome de la face postérieure du bras",
    "Réception sur le moignon de l’épaule",
    "Mécanisme direct",
    "Luxation de l’épaule du sujet âgé",
    "Bandage coude au corps",
    "Plaie de la face postérieure de la cuisse",
    "Face dorsale de la main",
    "Zone 6 des extenseurs",
    "Fracture de la tête de la 3ème phalange",
    "Luxation talo-naviculaire",
    "Luxation du complexe sous-astragalien",
    "Lambeau de MacGregor",
    "Fracture-luxation de la hanche",
    "Suspicion de coxalgie",
    "Voie de Hueter",
    "Traumatisme ouvert de l’avant-pied",
    "Lambeau de glissement",
    "Osteo-suture",
    "Cadrage au fil d’acier",
    "Lésion de ligament latéral externe",
    "Apophyse coronoïde",
    "Plaie de la fesse",
    "Plaie deltoïdienne",
    "Section du grand et petit palmaire",
    "Section du pédicule ulnaire",
    "Fracture arrachement de phalange",
    "Embrochage ISHIGURO",
    "Fracture de la 3ème phalange",
    "Membre déformé",
    "Dysthyroïdie",
    "Mécanisme indirect",
    "Fracture de la diaphyse humérale",
    "Surpoids",
    "Migration des broches",
    "Stade 2 de Salter et Harris",
    "Fracture base premier métacarpien",
    "Fracture extra-articulaire",
    "Embrochage type ISLAN",
    "Entorse grave du genou",
    "Pseudarthrose aseptique",
    "Rupture du ligament scapholunaire postérieur",
    "Fracture cunéenne interne",
    "PTH massive",
    "Infection sur matériel",
    "Crohn",
    "Ring finger",
    "Sclérose en plaques",
    "Plaie négligée",
    "Bord cubital",
    "Fracture du triquétrum",
    "Fracture-luxation rétro-lunaire du carpe",
    "Péroné intact",
    "Fracture de la styloïde ulnaire",
    "Section du 1er et 2ème radial",
    "Rameau latéral et médial du nerf radial",
    "Fracture du Gerrard marchant",
    "Chute à répétition",
    "Luxation du genou",
    "Angle 125°",
    "Attelle commissurale",
    "Maladie neurologique",
    "Équivalent bimalleolaire",
    "Porte d’entrée",
    "Fracture de la tête ulnaire",
    "Broche de Metezo",
    "Raideur",
    "Fracture de la tête du 1er métacarpien",
    "Scoliose",
    "Fracture du calcar",
    "Ramédiste",
    "Ménopause",
    "Fracture de l’extrémité supérieure du tibia",
    "Tumeur à cellules géantes",
    "2ème doigt",
    "Protos",
    "Cancer du sein",
    "Antécédent de fracture",
    "ECM à verrouillage distal",
    "Broche RUD",
    "Aveugle",
    "Tumeur maligne",
    "Masse d’allure inflammatoire",
    "Fracture thalamique",
    "Ostéochondromatose",
    "5ème orteil",
    "Fracture de la palette humérale",
    "Fracture sous-tubérositaire",
    "Sarcome",
    "Broche de Maîtrezeau",
    "Défenestration",
    "Névrome de Morton",
    "Greffe nerveuse",
    "Post-opératoire",
    "5ème métacarpien",
    "Embrochage de Foucher",
    "P1 du 3ème doigt",
    "Masse de l’épaule",
    "Chute sur un bord tranchant",
    "Corps charnus du FSD",
    "Douleur de la hanche",
    "Thrombophlébite",
    "Plaie de l’avant-pied",
    "Fracture des 4 premiers métatarsiens",
    "Hémopéritoine",
    "Nécrose du grêle",
    "Dyspnée",
    "Fracas",
    "Fracture médio-diaphysaire",
    "Fracture de la diaphyse fémorale",
    "Verrouillage distal",
    "Verrouillage dynamique",
    "Cannabis",
    "Patella bipartita",
    "Fracture ischiopubienne",
    "Suivi en psychiatrie",
    "Vissage du tubercule de Tillaux",
    "Luxations des tendons fibulaires",
    "Tassement",
    "Leiomyosarcome",
    "Garden 1",
    "Manœuvre de Bohler",
    "2ème métatarsien",
    "3ème métatarsien",
    "Cancer de la prostate",
    "Métastase pulmonaire",
    "Lavage digital",
    "Fasciite nécrosante",
    "Corps charnu",
    "Automutilation",
    "Les extenseurs",
    "Panaris",
    "Stade phlegmasique",
    "Fracture du Segond",
    "Tendon cubital antérieur",
    "Hyperthyroïdie",
    "Ostéonécrose de la tête fémorale",
    "Forage",
    "Tréphine",
    "Fracture de Bennett",
    "Embrochage de Tubiana",
    "Fracture de la phalange",
    "Fracture du métacarpe",
    "Traumatisme banal",
    "L'arrache-botte",
    "Mauvaise observance",
    "Carpite",
    "Maladie de Parkinson",
    "Muscle premier radial",
    "Supination adduction",
    "Torsion de la cheville",
    "Dyslipidémie",
    "État d'ivresse",
    "Sanglier",
    "Suture différée après 24h",
    "Sutures termino-terminales",
    "Hanche controlatérale",
    "Syndrome de Cushing",
    "Hernie discale",
    "Paraparésie",
    "Ulceration génitale",
    "Ecchymose",
    "Léo Burger",
    "Masse au niveau de la cheville",
    "ATCD de biopsie",
    "Voie antérieure de la cheville",
    "Douleur de la cheville",
    "Résection large",
    "Fracture de l'épitrochlée",
    "Fracture arrachement",
    "Fracture de l'épitrochlée",
    "Fracture épitrochlée",
    "Vissage dorsal du scaphoïde",
    "Hypotension",
    "Opéré pour cataracte",
    "Triade terrible",
    "Chute du 1er étage",
    "Fracture engrénée",
    "Embrochage en X de P1",
    "Arthrodèse de l'IPD",
    "Suture tendineuse",
    "Main toupie",
    "Somnambule",
    "Artère ulnaire",
    "FCP et FCS",
    "Grand et petit palmaire",
    "FUC",
    "SNOW",
    "Masse paume de la main",
    "Main droite",
    "Nécrose du scaphoïde",
    "Cheese",
    "Cataracte",
    "Mineur",
    "Retraité",
    "Droit",
    "Gauche",
    "Profil transthoracique",
    "Bassin",
    "Cadre obturateur",
    "Étudiant",
    "Fracture de Trillat",
    "Fracture de Malgaigne",
    "Nerf fémoro-cutané",
    "Fracture arrachement",
    "Fracture du 3ème métacarpien",
    "Excision",
    "Vie instable",
    "Matériel à nu",
    "Extrémité inférieure du fémur",
    "Cycliste",
    "Voie trans-tricipitale",
    "Métatarse",
    "Femme au foyer",
    "Belle image",
    "Masse",
    "Ostéochondrite du genou",
    "Ablation",
    "Arthrose cheville",
    "Arthroscopie diagnostique",
    "Recurvatum",
    "Menuisier",
    "Voiture",
    "Vicryl",
    "Plaque sous-cutanée",
    "Spina bifida",
    "PBVE",
    "Discopathie",
    "Séjour en réanimation",
    "Lésion cutanée",
    "Grand trochanter",
    "Camion",
    "Membre paralytique",
    "Ostéolyse",
    "Métastase vertébrale",
    "Métastase locorégionale",
    "Fragment ostéochondral",
    "Lésion méniscale externe",
    "Lésion méniscale bilatérale",
    "Échec du traitement",
    "Belle radio",
    "Retard de consolidation",
    "Synovial",
    "Polyarthralgie",
    "Mutualiste",
    "Lésion ancienne",
    "Tumeur pulmonaire",
    "Greffe cutanée",
    "Allaitement",
    "Broche styloïdienne",
    "Défenestration",
    "Crohn",
    "Ciel ouvert",
    "Hypoesthésie",
    "Grand palmaire",
    "Fléchisseur propre du pouce",
    "Os crochu",
    "Hamatum",
    "Base du 5ème métacarpien",
    "Transfert du long fléchisseur sur P1",
    "Orteil",
    "Gros orteil",
    "Gilderstone",
    "Hallux en griffe",
    "Arthrodèse de l'hallux",
    "Gardien",
    "Lymphangiome",
    "Luxation du pouce",
    "Fracture du tibia",
    "Plaie du bras",
    "Agriculteur",
    "Faux pas",
    "Ouverture du foyer de fracture",
    "Tendon fléchisseur zone 2",
    "Vissage tête radiale",
    "6 vis",
    "Fracture du capitellum",
    "Lipome de la main",
    "Face palmaire",
    "SNAC 2",
    "Arthrose scapho-radiale",
    "4 roues",
    "Clavicule",
    "1/4 inférieur de la jambe",
    "Fracture du calcanéus",
    "Plaque du calcanéum",
    "Angle de Bohler négatif",
    "Métatarsalgie",
    "Fracture de la base du P2",
    "Neurectomie",
    "Arthrite du coude",
    "État d'ivresse",
    "Felah",
    "Éthylisme",
    "ATCD épistaxis",
    "Plaque spéciale du calcanéum",
    "Trait fondamental vertical",
    "Constipation",
    "Stade IIa de Alnot",
    "SNAC I",
    "Ténolyse des fléchisseurs",
    "Fracture du premier métacarpien",
    "Section du tendon long extenseur de l'hallux",
    "Rupture du tendon d’Achille",
    "Nerf sural",
    "Stripping du nerf",
    "Commerçant",
    "Styloïde ulnaire",
    "Écart interfragmentaire",
    "Stade 5 Rockwood",
    "Fracture mandibulaire",
    "Iselin",
    "Plombier",
    "Lambeau sural",
    "Chauffeur d'autocar",
    "Fracture de la base de M1",
    "Morsure de cheval",
    "Fracture du Rolando",
    "Lésion du dôme astragalien",
    "Arthroscopie blanche",
    "Greffe intertibiofibulaire",
    "Voie postéro-latérale",
    "Décortication de Judet",
    "Rupture des deux péroniers",
    "Fracture bitubérositaire",
    "Fracture de la tubérosité tibiale antérieure",
    "Tendon du plantaire grêle",
    "Chimiothérapie",
    "Haglund",
    "Ponction articulaire",
    "Attelle en équin",
    "Masse au dépend du genou",
    "Déficit d'extension du genou",
    "Carreleur",
    "Lavage",
    "ATCD de fracture",
    "Diabète déséquilibré",
    "Fracture bilatérale de la diaphyse tibiale",
    "EIPS",
    "Tumeur de la cuisse",
    "Fièvre",
    "Sarcome à cellules claires",
    "Adénopathie",
    "Fracture des deux jambes",
    "Néo du poumon",
    "Arthrolyse du coude",
    "Transposition du nerf cubital",
    "Raideur du genou",
    "Maladie de Kienbock",
    "Résection de la 1ère rangée",
    "Muet",
    "Fracture du condyle interne du fémur",
    "Fracture du Hoffa",
    "Fracture de Trillat",
    "Fracture trochantéro-diaphysaire",
    "Chondrosarcome",
    "Pneumectomie",
    "Fracture sous-tubérositaire",
    "Plaie de l'avant-bras",
    "Perte de substance musculaire",
    "Syndrome du canal tarsien",
    "Os surnuméraire",
    "Orteil en marteau",
    "Pied neurologique",
    "Perte de substance cutanée",
    "HED",
    "Arthrolyse du genou",
    "Kyste méniscal",
    "Section du 2ème radiale",
    "Section du court extenseur du pouce",
    "Section de l'abducteur du pouce",
    "Section de l'extenseur du 3ème doigt",
    "Fracture bilatérale des deux poignets",
    "Embrochage intrafocal",
    "Fracture Monteggia",
    "Luxation spatullo-columnaire",
    "Doigt en boutonnière",
    "Abcès",
    "Égyptien",
    "Tumeur tenosynoviale à cellule géante",
    "Masse des parties molles",
    "Masse au niveau de la cuisse",
    "Anse de seau",
    "Hyperparathyroïdie",
    "Dissection",
    "Test",
    "Arthroscopie de la sous-talienne",
    "Paraplégie",
    "Thyroïdectomie",
    "Kyste mucoïde",
    "Sinus du tarse",
    "Sous-talienne",
    "Arthrodèse de la sous-talienne",
    "Instabilité de la sous-talienne",
    "Psoriasis",
    "Rhumatisme psoriasique",
    "Masse de l'épaule",
    "Délabrement de la cheville",
    "Luxation tibio-talienne",
    "Luxation ouverte de la cheville",
    "Doigt à ressaut",
    "Rétraction tendineuse",
    "Kyste du LCA",
    "Luxation ouverte de l'épaule",
    "Luxation négligée de l'épaule",
    "Traitement traditionnel",
    "Maladie exostosante",
    "Exostose",
    "Plaie souillée",
    "Perte de substance nerveuse",
    "Fixation des bouts du nerf",
    "Réception d'un objet tranchant",
    "Section du corps musculaire",
    "DIDT",
    "Douleur de l'épaule",
    "Douleur",
    "Traumatisme",
    "Impotence fonctionnelle",
    "Prélèvement bactériologique",
    "Rupture LCA",
    "Rupture LCP",
    "LERA",
    "Genu varum",
    "Acromion en crochet",
    "Allongement du fémur",
    "Luxation de l'épaule",
    "Maladie de Behçet",
    "Uvéite",
    "Amygdalectomie",
    "Gonalgies",
    "Césarienne",
    "Acromioplastie",
    "Hydarthrose",
    "Ulcère de la face plantaire du pied",
    "Amputation trans-tibiale",
    "Néo du pancréas",
    "Instabilité du genou",
    "VALFE",
    "Drainage de l'abcès",
    "Abcès des parties molles",
    "Immunodépression",
    "Mollets",
    "Cubitus varus",
    "Biopsie-exérèse",
    "Masse de l'index",
    "Ostéome ostéoïde",
    "Curetage-résection",
    "Pseudoblocage",
    "Ménisectomie",
    "Ostéosynthèse par plaque DCP",
    "Dilatation des bronches",
    "KJ",
    "Accident domestique",
    "Achondroplasie",
    "Triceps",
    "Réanimation de flexion du coude",
    "Ostéochondrite",
    "Réanimation de la main",
    "Long palmaire",
    "Flexor carpi ulnaris",
    "Réanimation de l'extension du poignet",
    "Parkinson",
    "Fracture col fémur",
    "Ostéosarcome",
    "Diabète",
    "Tendinoscopie",
    "Fracture diaphyse humérus",
    "Haubanage",
    "Masse épaule",
    "Arthroscopie épaule",
    "Sus-épineux",
    "Sujet masculin",
    "Régularisation du ménisque",
    "Veine saphène externe",
    "Paralysie ulnaire",
    "Caséum",
    "Coma",
    "Traitement endoscopique",
    "Arthrolyse du coude sous arthroscopie",
    "Arthroscopie du coude",
    "Masse de la région fessière",
    "Infection du matériel d'ostéosynthèse",
    "Ancienne PTH",
    "Traitement arthroscopique",
    "Cancer prostatique",
    "Thrombopénie",
    "Prostatectomie",
    "PTG postéro-stabilisée",
    "Prothèse de marche",
    "Corticothérapie",
    "Purpura thrombopénique auto-immun",
    "Hormonothérapie",
    "Canal carpien sous endoscopie",
    "Endoscopie",
    "Paresthésies",
    "Mobilisation sous AG",
    "Ostéonécrose de la tête fémorale",
    "Biopsie de la coxo-fémorale",
    "Lésion cartilagineuse",
    "SPE",
    "Syndrome canalaire",
    "Compression nerveuse",
    "Coiffe des rotateurs",
    "Acromioplastie arthroscopique",
    "Gaine des fléchisseurs",
    "Massue du pied",
    "Face dorsomédiale du 1er rayon",
    "Pseudarthrodèse",
    "Pied bot",
    "Reprise chirurgicale",
    "Pied bot varus équin",
    "Bris matériel",
    "Nécrose talus",
    "Arthrodèse métatarso-phalangienne",
    "Luxation métatarso-phalangienne négligée",
    "Pied creux",
    "Ténotomie",
    "Prothèse non cimentée",
    "Butée osseuse",
    "Extenseur ulnaire du carpe",
    "Tétraplégie",
    "Luxation du rachis cervical",
    "Fracture de la tête fémorale",
    "Mise à plat",
    "Fracture de la mandibule",
    "Fracture de l'apophyse zygomatique",
    "Amputation type Chase",
    "Plaque en trèfle",
    "Goitre",
    "Hernie crurale",
    "Œdème",
    "Biopsie avant-bras",
    "Microtraumatisme",
    "Image ostéocondensante",
    "Attelle postérieure",
    "Fracture diaphyse fémur",
    "Section des extenseurs",
    "Séquestre",
    "Agression",
    "Réimplantation de la main",
    "Lassage au Vicryl",
    "Arthrite de l'épaule",
    "Exploration au bloc",
    "Traumatisme domestique",
    "Section du nerf radial",
    "Section de l'artère radiale",
    "Fracture du coude",
    "Fracture de l'épicondyle médial",
    "Tuméfaction de l'épaule",
    "Fléchisseurs",
    "Auto-agression",
    "2 poignets",
    "Lésions vasculo-nerveuses",
    "Fracture de l'extrémité inférieure du radius",
    "Fracture de la tête du 5ème métacarpien",
    "Tabagisme sevré",
    "Fracture pathologique de l'humérus",
    "Ostéoporose",
    "Fracture des 2 os de l'avant-bras",
    "Toxicomanie",
    "Lambeau du jumeau interne",
    "Lambeau du soléaire",
    "Lambeau musculaire",
    "Greffe cutanée",
    "Luxation de la hanche",
    "Région poplitée",
    "Cross finger",
    "Délabrement des phalanges",
    "Artériographie",
    "Luxation antérieure pure",
    "Pivot central",
    "Synovialosarcome",
    "Bilan d'extension négatif",
    "Erysipèle",
    "AVC",
    "Grosse jambe",
    "Fracture du fémur",
    "Fracture base du 5ème métatarsien",
    "Contusion des parties molles",
    "Rétinopathie diabétique",
    "Cécité",
    "Prothèse de reconstruction massive",
    "Résection carcinologique",
    "Mécanisme de défense",
    "Arthrodèse carpo-métacarpienne",
    "Luxation carpo-métacarpienne M4/M5",
    "Hépatite B",
    "Anémie",
    "ATB",
    "Plaie de la cheville",
    "Canal tarsien",
    "Lésion artère tibiale postérieure",
    "Fracture de l'extrémité inférieure du fémur",
    "Fracture de la diaphyse tibiale",
    "Abducteur de l'hallux",
    "Fracture malléole externe",
    "Fracture diaphyse tibia",
    "Creux poplité",
    "Hémarthrose",
    "Blocage",
    "Biopsie synoviale",
    "Prothèse de l'épaule",
    "Sédation",
    "4 fragments",
    "Prothèse traumatique",
    "Pouteau-Colles",
    "Mastectomie",
    "Curetage",
    "Flessum",
    "Vis directe",
    "Région scapulaire",
    "Membre dominant",
    "Kyste pilosébacé",
    "Arthrite de la hanche",
    "MCGREGOR",
    "ANGIOMYOME",
    "Extrémité sup du fémur",
    "Genou instable",
    "Laxité externe",
    "Syndésmodèse",
    "Mis à nu du matériel d'ostéosynthèse",
    "Tendinopathie calcifiante de la coiffe",
    "Nécrose",
    "Nécrose musculaire",
    "Cimentée",
    "FH Orthopedic",
    "Néphropathie",
    "Sarcome d'Ewing",
    "Amplitude",
    "RAA",
    "Descellement",
    "Coxite",
    "Mal de Pott",
    "Clou rétrograde du fémur",
    "Spacer",
    "Lésion mono-faisceau",
    "Alzheimer",
    "Spasticité",
    "Fracture des phalanges",
    "Fracture du métacarpe",
    "Hauteur élevée",
    "Enfoncement",
    "Amaigrissement",
    "Parker",
    "Chute des escaliers",
    "Psychose",
    "Neuroleptiques",
    "Lacage",
    "Fracture de l'extrémité sup du fémur",
    "Face postérieure de la jambe",
    "Sacro-iliaque",
    "Rachis dorsal",
    "Ténotomie du long biceps",
    "Cancer rénal",
    "Masse du genou",
    "Embolisation",
    "Météseau",
    "Carcinome spinocellulaire",
    "Amputation trans-humérale",
    "Curage axillaire",
    "Fracture ouverte de la jambe",
    "Délabrement",
    "Amputation post-traumatique",
    "Kyste essentiel",
    "Collection du genou",
    "Fracture de la base du 5ème métatarsien",
    "3ème, 4ème, 5ème MP",
    "Chute d'une hauteur élevée",
    "Contrebandier",
    "Fracture de l'épaule",
    "Fracture de la glène",
    "Nécrose aseptique de la tête fémorale",
    "Ostéosynthèse du rachis",
    "Double mobilité",
    "Non cimenté",
    "Non cimentée",
    "Tuberculose ganglionnaire",
    "Voie de Hutter",
    "Triple vissage",
    "Corps étranger",
    "Instabilité",
    "Condyle externe",
    "Douleur mécanique",
    "Vrai blocage",
    "Réanimation du nerf radial",
    "Hackettal",
    "Réanimation de la main",
    "Plaque du cotyle",
    "Traumatisme grave",
    "Hernie inguinale",
    "Vissage direct",
    "Lavage articulaire",
    "Plastie de l'ongle",
    "Lésions méniscales",
    "Lésions cartilagineuses",
    "Genou arthrosique",
    "Lésion vasculaire",
    "Traumatisme ancien de l'avant-bras",
    "Incision de décharge",
    "Altération de l'état général",
    "Infiltration des parties molles",
    "Artère poplitée",
    "Extrémité froide",
    "Épileptique",
    "Retard mental",
    "Fracture du 1/4 distal de la jambe",
    "Lésion des fléchisseurs",
    "Lésion nerveuse",
    "Masse de l'avant-bras",
    "Embrochage Hackettal",
    "Intubé-ventilé",
    "Face antérieure",
    "Lésion de l'artère radiale",
    "Traumatisme du rachis",
    "Gonflement",
    "Plâtre pendant",
    "Cubital antérieur",
    "Tumeur du larynx",
    "Laryngectomie",
    "Trachéotomisé",
    "Stable",
    "Fracture luxation métacarpo-phalangienne",
    "Hémiplégie",
    "Lasso selon Zancolli",
    "Thomsson",
    "Angiomateuse",
    "Languette méniscale",
    "Séction négligée tendon fléchisseur",
    "PTH de reprise",
    "Reprise prothèse de Moore",
    "Tige longue",
    "Cotyloidite",
    "DT 3",
    "Ligamentoplastie DT3",
    "Plaie de la cuisse",
    "Main gauche",
    "Fractures costales",
    "Tubercule du grand adducteur",
    "Hypertrophie synoviale",
    "Ostéotomie de la TTA",
    "MPFL",
    "Ténodèse du tendon rotulien",
    "Amputation traumatique",
    "Flexum de la hanche",
    "Suture termino-terminale",
    "Atelle en équin",
    "Arthrodèse talo-naviculaire",
    "PBABP",
    "Alcoolique",
    "Angiome du genou",
    "Plaque verrouillée",
    "Fracture du rachis",
    "Transfert tendineux",
    "Extenseur propre de l’index",
    "Clou de l’humérus",
    "KHP",
    "KHF",
    "Face postérieure de la cuisse",
    "Demi-membraneux",
    "Droit interne",
    "Forage de la tête fémorale",
    "PTE inversée",
    "PTG massive",
    "La goutte",
    "Arthropathie microcristalline",
    "Footballeur",
    "Fracture bilatérale des deux fémurs",
    "Lésion bicrôisée",
    "Lésion LLE genou",
    "Plastie de LERAT",
    "Pouce à ressaut",
    "Tige cimentée",
    "Cotyle non cimenté",
    "Dysplasie du cotyle",
    "Greffe du toit de cotyle",
    "Tuberculose pulmonaire",
    "Sarcome des parties molles",
    "Luxation ouverte du 4ᵉ orteil",
    "Plaie de la loge thénar",
    "Fracture de la malléole interne",
    "Piéton",
    "Luxation négligée",
    "Luxation de Chopard",
    "Embrochage du cubitus",
    "Maladie de Freiberg",
    "Ostéotomie de Gauthier",
    "Os iliaque",
    "Exostose solitaire",
    "Fracture de la palette humérale",
    "Fracture de Hoffa",
    "Fracture de Lisfranc",
    "Arthroscopie du pied",
    "Maladie de Kahler",
    "Plasmocytome",
    "Chute d’un escalier",
    "Traction au lit",
    "Luxation de la tête cubitale",
    "Résection tête et col fémoral",
    "Hanche ballante",
    "Ostéoarthropathie neurogène",
    "Curage ganglionnaire",
    "Kyste synovial",
    "Patte d’oie",
    "Résection d’un kyste synovial",
    "Kyste extra-articulaire",
    "Myélome multiple",
    "Embrochage en L",
    "Ostéotomie tibiale de valgisation",
    "Ostéotomie ouverture médiale",
    "Passager d’un autocar",
    "PTG avec cal interne",
    "Release en damier",
    "Fracture de l’extrémité supérieure de l’humérus",
    "Tenosynovite de De Quervain",
    "Tendons fléchisseurs du 4ᵉ doigt",
    "Gonalgie",
    "Bicyclette",
    "Passager d’une voiture",
    "Fracture péri-prothétique",
    "Lésion des extenseurs",
    "Embrochage-haubanage",
    "Simtrum",
    "Plaque cotyle",
    "Kocher Langenbeck",
    "Hyperflexion",
    "Boiterie",
    "Ostéotomie de soustraction",
    "Plaie inguino-scrotale",
    "Garden 3",
    "Basi-cervicale",
    "Technique de Schnepp",
    "Épicondylite",
    "Rupture des extenseurs",
    "Lambeau de rotation",
    "Zancolli",
    "Transfert tendineux palliatif",
    "Synovite du genou",
    "Métatarsalgie",
    "Ostéotomie basimétatarsienne",
    "Hyperkératose plantaire",
    "Train",
    "Arthrolyse arthroscopique du genou",
    "Neurolyse du nerf ulnaire",
    "Compression du nerf ulnaire au niveau du coude",
    "Abcès de l’hallux",
    "Hémangiome synovial",
    "Fracture intertrochantérienne",
    "Kyste anévrysmal",
    "Lipome arborescent",
    "Résection tête et col",
    "Arthroscopie de l’épaule",
    "Mosaicoplastie",
    "Fracture marginale postérieure",
    "Origine neurologique",
    "ECM dynamique",
    "Fracture du péroné",
    "Fracture luxation du 4ᵉ métacarpien",
    "Amputation pulpaire",
    "Plaie du pouce",
    "Plaie du genou",
    "Guillain-Barré",
    "Pouteau-Colles",
    "Maladie de Paget",
    "Syndactylie de la main",
    "Plaie du 5ᵉ doigt",
    "Tenosynovite",
    "Ostéoblastome",
    "Tumeur vulvaire",
    "Gastrite chronique",
    "Ostéoarthrite",
    "Fracture du métacarpien",
    "Fracture de la tête du 5ᵉ métacarpien",
    "Hypercholestérolémie",
    "Raideur métacarpo-phalangienne",
    "Atelle palmaire",
    "Abcès du bras",
    "Tumeur cérébrale",
    "Plaie de la face antérieure de l’avant-bras",
    "Plaie des fléchisseurs",
    "Tumeur du sein",
    "Cholécystectomie",
    "Phlegmon de la main",
    "Chute d’une échelle",
    "Rupture tendineuse",
    "Section du long fléchisseur du pouce",
    "Rupture vésicale",
    "Fracture de la diaphyse radiale",
    "Chute d’une chaise",
    "Myopathie",
    "Cirrhose",
    "Lésion méniscale",
    "Amputation trans-tibiale",
    "Électrocution",
    "Paralysie sciatique",
    "Luxation tarso-métatarsienne",
    "Patey",
    "Lambeau d’Atasoy",
    "Contusions cérébrales",
    "Hémorragies alvéolaires",
    "Hémorragie méningée",
    "Embarrures",
    "Fracture des OPN",
    "Emphysème pulmonaire",
    "Hémothorax",
    "OTV par ouverture interne",
    "Plaie du cuir chevelu",
    "Plaie du coude",
    "Synostose radio-ulnaire",
    "Plastie de la membrane interosseuse",
    "Séquestrectomie",
    "Fistulectomie",
    "Adénomectomie",
    "Extrémité supérieure de l’humérus",
    "Débricolage",
    "Voie ilio-inguinale",
    "Appendicectomie",
    "Délabrement cutané",
    "Syncope",
    "Luxation négligée de Lisfranc",
    "Tendons fléchisseurs superficiels",
    "Plaie du mollet",
    "Hémo-pneumothorax",
    "Conflit sous-acromial",
    "Réinsertion coiffe",
    "Fracture du 5ᵉ métacarpien",
    "Plaie de l’index",
    "Luxation pure",
    "Amputation du pouce",
    "Chute sur le moignon de l’épaule",
    "Rupture de la coiffe des rotateurs",
    "Ancien traumatisme de la hanche",
    "Disjonction pubienne",
    "Attelle postérieure",
    "Vis malléolaire",
    "Delto-pectorale",
    "Conflit ulno-carpien",
    "Ostéotomie de raccourcissement de l’ulna",
    "Vis de rappel",
    "Supination-RE",
    "Morphotype longiligne",
    "Ablation de corps étranger",
    "Désinsertion du gastrocnémien",
    "Amputation du 2ᵉ doigt",
    "Amputation du 3ᵉ doigt",
    "Paralysie radiale post-opératoire",
    "Contusion cérébrale",
    "Fracture du sinus maxillaire",
    "Hémosinus",
    "Membrane induite",
    "Arthrodèse du couple de torsion",
    "Épiphysiodèse",
    "Épiphysiodèse chirurgicale",
    "Plica infra-patellaire",
    "Traitement palliatif",
    "Splénectomie",
    "Peau fine",
    "Limitation du périmètre de marche",
    "Lambeau fascio-cutané de dérotation",
    "Ulcère gastrique",
    "Délabrement de la jambe",
    "Accident de masse",
    "Rétraction du tendon d’Achille",
    "Allongement percutané",
    "Réinsertion méniscale",
    "Tumeur colique",
    "Lyse de l’os iliaque",
    "Cancer col utérus",
    "Pancytopénie",
    "Scarf sans ostéosynthèse",
    "Weil",
    "Hallux rigidus",
    "Arthrodèse métatarso-phalangienne",
    "Vis corticale",
    "Déformation du 2ᵉ orteil",
    "Amputation doigt",
    "Hernie ombilicale",
    "Polyfracturé",
    "Instabilité de l’épaule",
    "Fracture du D12",
    "Traumatisme de l’uretère",
    "Rupture LCA partielle",
    "Hyperkaliémie",
    "Fracture des plateaux tibiaux",
    "Arthrite de l’acromio-claviculaire",
    "Épaule",
    "Insuffisance rénale",
    "Amputation ungéale",
    "Cancer du colon",
    "Colectomie",
    "Luxation postérieure de la hanche",
    "Traction trans-condylienne",
    "Réception d’un objet lourd",
    "Médio-pied",
    "Cuboïde",
    "Cancer colique",
    "Colostomie",
    "Tête humérale",
    "Talus",
    "Métastases cérébrales",
    "Métastases osseuses",
    "Arthrolyse de la cheville",
    "Contusion hépatique",
    "Luxation antéro-interne",
    "Cancer de la vulve",
    "Vulvectomie",
    "Embolie pulmonaire",
    "Fracture luxation radio-carpienne",
    "Kyste hydatique",
    "Démence",
    "Arthrose de l’articulation sous-talienne",
    "Arthrose de Lisfranc",
    "Double arthrodèse",
    "Rhizarthrose",
    "Trapézectomie",
    "Apnée de sommeil",
    "Varus de l’arrière-pied",
    "Ostéosuture",
    "Ostéotomie de varisation du P1",
    "Ostéotomie bipolaire de Schnepp",
    "Hallux valgus congénital",
    "Épiphysiolyse de la tête fémorale",
    "Fracture spontanée",
    "Fibrome",
    "LCP",
    "Traumatisme bipolaire",
    "Fracture de l’olécrâne",
    "Fracture splénique",
    "Contusion pulmonaire",
    "Luxation de l’ATM",
    "Rupture diaphragmatique",
    "Fracture des apophyses transverses",
    "Rachis lombaire",
    "Maladie de Crohn",
    "Crâne",
    "Trochantérite",
    "Prélèvement bactériologique",
    "Syndrome des loges",
    "Aponévrotomie",
    "Amputation des doigts",
    "CALE",
    "Fibrosarcome",
    "Scapulectomie",
    "Symphyse pubienne",
    "Étude anatomo-pathologique",
    "Leucémie aiguë myéloïde",
    "Plaque percutanée",
    "Traumatisme ancien de la hanche",
    "Mélanome",
    "Lambeau supramalléolaire externe",
    "Voie de Rotinger",
    "Main de menuisier",
    "Nécrose de la pulpe du pouce",
    "Conducteur de voiture",
    "Chondromatose",
    "Voie para-patellaire interne",
    "Voie de Trickey",
    "Résection de la masse",
    "Lésion ostéochondrale de l’astragale",
    "Lambeau de Littler",
    "Gernez externe",
    "Masse pubienne",
    "Cheville gauche",
    "Dynamisation",
    "Plaque calcanéenne",
    "Jeune femme",
    "Fracture du col fémoral",
    "Voie de Ducrockey et Lunay",
    "Ostéochondromatose de l’épaule",
    "Femme",
    "Moins de 60 ans",
    "Quinquagénaire",
    "Cotyle Atlas",
    "Voie d’abord postéro-externe de Moore",
    "Lambeau ulnaire",
    "Lésion du LLI",
    "Clichés dynamiques",
    "Fracture jambe",
    "Fracture des deux os de la jambe droite",
    "Fracture tibiopéronéale",
    "Polytraumatisé",
    "Salter 3",
    "Réveils nocturnes",
    "Reprise de PTH",
    "Trouble de conscience",
    "Métallose",
    "Néoplasie du col utérin",
    "Maisonnewue",
    "Tumeur cutanée",
    "Arthrose de l’épaule",
    "Pseudarthrose de l’épaule",
    "Hypertrophie bénigne de la prostate",
    "Choc septique",
    "Tophus goutteux",
    "Plaque anatomique",
    "Voie delto-pectorale",
    "Manœuvre externe",
    "Réception sur la main droite",
    "Fracture luxation de la tête fémorale",
    "Sujet jeune",
    "Fracture de la tête fémorale",
    "Luxation de la tête fémorale",
    "Agitation",
    "Fracture bifocale du tibia",
    "Opéré pour DDB",
    "Lésion de LCA",
    "Tendinite des fibulaires",
    "Tendinoscopie des fibulaires",
    "Ablation de matériel",
    "Fracture ouverte de la main",
    "Vomissement",
    "Canal lombaire étroit",
    "Ligamentoplastie Macintosh",
    "Jbira",
    "Pseudarthrose ancienne",
    "ATCDs familial",
    "Tumeur de la face palmaire de la main",
    "Rupture post-traumatique tendon grand pectoral",
    "Tumeur vasculaire",
    "Gabari",
    "Tumeur de l'omoplate",
    "Tumeur de la scapula",
    "Suture de la coiffe",
    "Synostose astragalo-calcanéenne",
    "Arthrolyse",
    "Luxation congénitale de la hanche",
    "Capsulite rétractile",
    "Méthotrexate",
    "Tumeur du poumon",
    "Compression médullaire",
    "Tassement vertébral",
    "Fracture tassement du plateau tibial",
    "Cancer du cavum",
    "Chimiothérapie",
    "Pseudarthrose du fémur",
    "Embrochage de Métaizeau",
    "Collision de voiture",
    "Greffe de l'arrière-fond",
    "Arthrose tibio-astragalienne",
    "Greffe de la crête iliaque",
    "PTH cimentée",
    "Image lytique",
    "Maigre",
    "Subamputation du poignet",
    "Cicatrice lombaire",
    "Collection",
    "Plaie talon du pied",
    "Œdème cérébral",
    "Genou varum",
    "Rupture du LCA",
    "Ménisque interne",
    "Shaving",
    "Dos de fourchette",
    "Antidépresseur",
    "Pied en varus",
    "Steppage",
    "Déficit sensitivo-moteur",
    "Hypothyroïdie",
    "Luxation cardiaque",
    "Atelle intrinsèque plus",
    "Greffe du radius distal",
    "Fracture luxation de la tête humérale",
    "Béquilles",
    "Corticotomie",
    "Lombalgie",
    "Traumatisme du poignet",
    "Gernez interne",
    "Voie externe du fémur",
    "Judet",
    "Pneumopéritoine",
    "Laparotomie exploratrice",
    "Section des tendons fléchisseurs",
    "Délabrement cutané de la jambe",
    "Antibiotique",
    "Pied spastique",
    "Pied creux varus",
    "Transfert du jambier postérieur",
    "Talalgie",
    "Maladie d'Haglund",
    "Veine jugulaire interne droite",
    "Chute dans les escaliers",
    "Dysjonction de la symphyse pubienne",
    "Fracture du sacrum",
    "Arrachement de l'épine tibiale",
    "Contusion médullaire",
    "Fracture vertébrale",
    "Pontage vasculaire",
    "Tumeur du bassin",
    "Conservation de l'état général",
    "Ostéotomie de Dwyer",
    "Crush syndrome",
    "Unitubérositaire externe séparation",
    "Sarcome de Kaposi",
    "Fracture spino-tubérositaire interne stade C",
    "Paralysie SPE",
    "Lyse osseuse",
    "Voie postéro-interne",
    "Fracture de la tête du 5e métacarpien",
    "Ulcère du membre inférieur",
    "Ulcère de la jambe",
    "Fracture du 5e métatarsien",
    "Lambeau neuro-sural",
    "Pontage fémoro-poplité",
    "Occlusion de l'artère fémorale superficielle",
    "Hépatite C",
    "Retard de croissance",
    "Tumeur gingivale",
    "Médulloblastome",
    "Limitation des amplitudes articulaires",
    "Allongement du tendon d'Achille",
    "Garden 2",
    "Désarticulation du poignet",
    "Nécrose talonnière",
    "Sans couverture sanitaire",
    "Prothèse Charley",
    "PTH bilatérale",
    "Ostéotomie de Scarf",
    "Dégénérescence cancéreuse",
    "Désarticulation de la hanche",
    "Résection de la styloïde radiale",
    "Région fessière",
    "Anatomopathologie",
    "Angiocholite",
    "Maladie de système",
    "Lachman",
    "Tiroir antérieur",
    "Ostéotomie du calcanéum",
    "Synostose calcanéo-naviculaire",
    "Ténodèse du long biceps",
    "Luxation méniscale",
    "Tuméfaction de la cheville",
    "Infiltration tendineuse",
    "Fracture de côtes",
    "Hématome sous-dural",
    "Arthroscopie de la cheville",
    "Conflit cheville",
    "Rupture du tendon d'Achille",
    "Sprinter",
    "Calcinose pseudo-tumorale",
    "Tache café au lait",
    "Flexum du genou",
    "Syndrome de Gougerot",
    "Fracture sous-trochantérienne",
    "Mélanome unguéal",
    "Fracture arrachement des épines tibiales",
    "Retour externe",
    "Reprise de ligamentoplastie",
    "Revascularisation",
    "Pontage",
    "Artère humérale",
    "Fracture de l'humérus proximal",
    "Carcinome basocellulaire",
    "Cancer du pancréas",
    "Ténotomie du tendon d'Achille",
    "Ténotomie du tibial antérieur",
    "Ténotomie du tibial postérieur",
    "Pulvertaft",
    "Fracture de la paroi antérieure",
    "Dossier intéressant",
    "Mini-invasive",
    "Voie de Caplan",
    "Staphylocoque",
    "Hyperextension du genou",
    "Triple verrouillage de Patt",
    "Arrachement de l’épitrochlée",
    "PTG bilatéral",
    "Ostéodystrophie",
    "PFNA",
    "Synovite des extenseurs",
    "Voie antérieure du scaphoïde",
    "Chondropathie",
    "Arthrose tri-compartimentale",
    "Ostéophytose",
    "Monoplégie",
    "Syndrome de Gougerot Sjögren",
    "Coxa profunda",
    "Infection sur prothèse",
    "Dépose de prothèse",
    "Reconstruction du cotyle",
    "Mallet finger",
    "Gérard Marchand",
    "Resurfaçage de la rotule",
    "Dénervation",
    "Anesthésie intra-articulaire",
    "PTG difficile",
    "Bacille multi-résistant",
    "Fracture du rachis lombaire",
    "Délabrement cutané",
    "Autogreffe",
    "Abcès de l'avant-bras",
    "Fracture du capitatum",
    "Klebsiella pneumoniae",
    "Temps de Hunter",
    "Pseudarthrose du métacarpien",
    "Voie postérieure transolécranienne",
    "Résection des têtes métatarsiennes",
    "Périartérite noueuse",
    "Biopsie nerveuse",
    "Grosse bourse",
    "Attitude du traumatisé",
    "Attitude du traumatisé du membre supérieur",
    "Ataxie cérébelleuse",
    "Syndrome cérébelleux",
    "Trouble de l'équilibre",
    "Traumatisme fermé",
    "Érythème",
    "Fracture de la rate",
    "Luxation sterno-claviculaire",
    "Sternum",
    "Hypodermite nécrosante",
    "Hémopneumothorax",
    "Fracture à 4 fragments",
    "Épaississement colique",
    "Ascite",
    "Pancréatite",
    "Allitement",
    "Bulle d'air",
    "Ballonnement abdominal",
    "Fracture du condyle externe",
    "Infection des parties molles",
    "Fractures des métacarpiens",
    "Endobouton",
    "5e métatarsien",
    "Évasion",
    "Ecchymose",
    "Droitier",
    "Plastie en Z",
    "Ambulancier",
    "Ancre",
    "Sans garrot",
    "Sans drain de Redon",
    "Cal",
    "Douleur du poignet",
    "Ostéite",
    "Circulation veineuse collatérale",
    "Non douloureuse",
    "Transfert du cubital antérieur",
    "Transfert du petit palmaire",
    "Paralysie basse du nerf radial",
    "Foyer ouvert",
    "Réduction sanglante",
    "Embrochage Vives",
    "Résection du 1/4 externe de la clavicule",
    "Pseudarthrose de la rotule",
    "Rupture de l'appareil extenseur",
    "Adhérence intra-articulaire",
    "Lombosciatalgies",
    "Synevectomie",
    "Patella bipartita",
    "Morsure de chien",
    "Silicose",
    "Fracture de Maisonneuve",
    "Fracture de Rolando",
    "Sacro-iliite",
    "Dysplasie fibreuse",
    "Myosite calcifiante",
    "Voie d'abord rétropéritonéale",
    "Décèlement de prothèse",
    "Hydroxyapatite",
    "Luxation de semi-lunaire",
    "Énucleation du semi-lunaire",
    "Os du carpe",
    "Lunatum",
    "Abord en épaulette",
    "Lassage à la soie tissée",
    "Ostéotomie fémorale de varisation",
    "Thrombose artérielle",
    "Prothèse artérielle",
    "Thrombectomie",
    "Luxation postérieure de l'épaule",
    "Capsulorraphie",
    "Hématome de la cuisse",
    "Fracture du rachis cervical",
    "Fracture de la colonne antérieure",
    "Céramique-céramique",
    "Ligament annulaire",
    "Calcinose",
    "Adolescent",
    "Luxation carpo-métacarpienne",
    "Technique de Hunter",
    "Chauffeur",
    "Chute d'un cheval",
    "Défense abdominale",
    "Décortication",
    "Fracture ouverte du bras",
    "Fracture du sésamoïde hallux",
    "Plaie de l'épaule",
    "Éclatement du globe oculaire",
    "Voie d'abord postérieure du genou",
    "Fracture du massif des épines",
    "Septique",
    "Voie de Keblish",
    "Pas de resurfaçage de la rotule",
    "Fracture luxation trans-scapho-antélunaire",
    "Fracture de métacarpien",
    "Arthrorise",
    "Rupture sous-cutanée du long extenseur du pouce",
    "Nécrose cutanée",
    "Nécrosectomie",
    "Die-punch",
    "Fracture de l'extrémité externe de la clavicule",
    "Ostéonécrose de la tête humérale",
    "Gastrocnémien médial",
    "Sourd",
    "Tubercule de Thillaux",
    "Reprise de prothèse de Moore",
    "Descellement septique",
    "Fibrome utérin",
    "Engelure",
    "Exposition au froid",
    "Tendon quadricipital",
    "Voie de Ganz",
    "Cotyle opéré",
    "Appareil extenseur",
    "Tuméfaction du mollet",
    "Macintosh",
    "Militaire",
    "Embrochage centromédullaire élastique stable",
    "ECMES",
    "Ostéotomie de Weil",
    "Récidive",
    "Trucs et astuces",
    "Sacrum",
    "Fracture de la tête radiale",
    "Pubalgies",
    "Adducteurs",
    "Fracture luxation gléno-humérale",
    "Indolore",
    "Malformation lymphatique",
    "Infiltration aux corticoïdes",
    "Bankart",
    "Voie antéro-externe de l'épaule",
    "Plantaire",
    "Ossification hétérotopique",
    "PTG charnière",
    "Traumatologie A",
    "Fasciite nodulaire",
    "Fasciite proliférative",
    "Test de Hook",
    "Fracture du pouce",
    "Fracture de P2",
    "LLI",
    "Technique de Helfet",
    "La région inguinale",
    "Pus chocolat",
    "Embolectomie",
    "Reprise de PTG",
    "Double voie d'abord",
    "Changement polyéthylène",
    "Fracture péri-opératoire",
    "Optimisation du diamètre du greffon DIDT",
    "Hématome sous-dural",
    "Infection urinaire",
    "Résection arthroscopique",
    "Klebsiella pneumoniae",
    "Imipénème",
    "Tumeur myoépithéliale",
    "Parties molles",
    "Tissu mous",
    "Sous-épineux",
    "Sténose carotidienne",
    "Aphasie",
    "Hémopathie",
    "Hémophilie",
    "Homme",
    "Tuméfaction",
    "Luxation négligée du poignet",
    "Voie antérieure du poignet",
    "Leucémie lymphoïde chronique",
    "Purpura thrombopénique",
    "Dossier intéressant",
    "Fracture céphalo-métaphysaire",
    "Luxation irréductible",
    "Luxation métacarpo-phalangienne",
    "Luxation radio-ulnaire distale",
    "Fracture de Galeazzi",
    "Fracture de Segond",
    "Scapulectomie totale",
    "Tumeur bénigne",
    "Accident de la voie publique",
    "Fragment en aile de papillon",
    "Plaque du cubitus distale",
    "Prélèvement bactériologique",
    "Voie d'abord de Stoppa",
    "Veine iliaque externe",
    "Lésion vésicale",
    "Voie d'abord antéro-médiane du genou",
    "Atteinte monoarticulaire",
    "Épaississement de la synoviale",
    "Reprise de ligamentoplastie LCA",
    "Synovialosarcome",
    "Pseudarthrose du massif trochantérien",
    "Lymphome",
    "Touche de piano",
    "Fracture du cadre obturateur",
    "Métaphysaire",
    "Métastase cérébrale",
    "Engrainée",
    "Hémodialysé chronique",
    "Fracture péri-prothétique",
    "Recul",
    "Dépression",
    "Fracture consolidée",
    "Méningite",
    "Morsure de serpent",
    "Nerf radial intact",
    "Fracture du trapèze",
    "Synovite du coude",
    "Biothérapie",
    "Syndrome inflammatoire",
    "Coude droit",
    "Rupture du tendon quadricipital",
    "Rupture du tendon rotulien",
    "Genou gauche",
    "Genou droit",
    "Reperméabilisation du canal médullaire",
    "Covid-19",
    "Insuffisance cardiaque",
    "Luxation péritalienne",
    "Fracture de Monteggia",
    "Luxation de la tête radiale",
    "Ostéite chronique",
    "Ostéomyélite",
    "Présentation",
    "Rupture du LLI",
    "Épilepsie",
    "Double voie d'abord",
    "Trouble trophique",
    "Plaie scrotale",
    "Rupture ligament latéral collatéral",
    "Luxation irréductible",
    "Montage en vasque",
    "Déplacement du matériel",
    "Plaque de l'humérus",
    "AG",
    "Tumeur brune",
    "Souffrance cutanée",
    "Fracture du pubis",
    "Désarticulation de hanche",
    "Attelle",
    "Hématome extradural",
    "RAU",
    "Plaque de radius",
    "Pathologie rhumatismale",
    "Écharpe coude au corps",
    "Fracture de la tête du 5e méta",
    "Arthrite septique",
    "Baumanii",
    "Adénome de la prostate",
    "Football",
    "Ains",
    "Arthroscopie de l'épaule",
    "Paresthésies",
    "Leucémie myéloïde chronique",
    "Marche avec béquille",
    "Coxarthrose bilatérale",
    "Reprise de tendons extenseurs de l'index",
    "Tumeur glomique",
    "Sous-unguéal",
    "Raideur matinale",
    "Vis d'interférence",
    "Hémopéritoine",
    "Polydactylie",
    "Difficulté de chaussage",
    "Os naviculaire accessoire",
    "Trouble rotatoire",
    "PTE bilatérale",
    "Syndrome de revascularisation",
    "Métacarpe",
    "Fracture de la 4e métacarpe",
    "Ancienne fracture",
    "Aile iliaque",
    "Fistule colique",
    "Plaque tordue",
    "Accidents aux AVK",
    "Doigt en col de cygne",
    "Zancolli et Tonkin",
    "Ténodèse",
    "Tonkin",
    "Antibiogramme",
    "Staphylococcus aureus",
    "Lésions urologiques",
    "Lésions de la filière génitale",
    "Résection de la première rangée du carpe",
    "Tumeur du système nerveux périphérique",
    "Podoscope",
    "Raideur mixte",
    "Mobilisation sous anesthésie",
    "Paralysie du plexus brachial",
    "Résection tumorale",
    "Bas niveau socio-économique",
    "Bas niveau socioéconomique",
    "Synovite",
    "Opéré ailleurs",
    "Toxoplasmose",
    "Thalassémie",
    "Abcès profond",
    "Fracture négligée du col fémoral",
    "Descellement aseptique",
    "Crête iliaque postérieure",
    "Étudiant",
    "CNOPS",
    "Fibrome chondromyxoïde",
    "Petit trochanter",
    "Voie interne Ludloff",
    "Découverte fortuite",
    "Coxarthrose secondaire",
    "Goutte",
    "Luxation de prothèse",
    "Sans ATCDs",
    "Protrusion acétabulaire",
    "Acrosyndrome",
    "Intertrigo",
    "Leucémie aiguë lymphoïde",
    "Brancardier",
    "Électricien",
    "Hernie hiatale",
    "Fracture bifocale",
    "Étudiante",
    "Agent de police",
    "P1 du pouce",
    "Arrachement",
    "Déplacement postérieur",
    "Technique de Robert Méary",
    "Voie antéro-latérale de la cheville",
    "Arthrodèse talo-crurale",
    "Arthrose talo-crurale",
    "Traffic elbow",
    "Renversement de voiture",
    "Contusion artérielle",
    "Contusion artérielles",
    "Antibacillaires",
    "Évolution lente",
    "Coxalgie",
    "Alités",
    "Fracture déplacée",
    "Luxation de l’IPD",
    "Tiers externe de la clavicule",
    "Chondroblastome",
    "Douleur type mécanique",
    "Diminution du périmètre de la marche",
    "Tumeur de la prostate",
    "Métastase osseuse",
    "Corona mortis",
    "Nerf obturateur",
    "Ténotomie d’allongement du tendon d’Achille",
    "Le muscle tibial antérieur",
    "Pied en équin",
    "Agent de sécurité",
    "Ostéotomie de Gautier",
    "Rupture de LLE",
    "Désarticulation de l’épaule",
    "Carbapénème résistant",
    "Ponts osseux",
    "Ostéotomie de transposition de la TTA",
    "Fracture du col",
    "Fracture de l’humérus",
    "Fracture du 3ᵉ métacarpien",
    "Tailor's Bunion",
    "Bunionette",
    "Dermatofibrosarcome de Darier et Ferrand",
    "Dermatofibrosarcome",
    "Sarcome d’Ewing",
    "Myélite optique",
    "Diabète et fracture",
    "Patella alta",
    "Traumatisme balistique",
    "Déplacement antérieur",
    "Protocole de Duron",
    "Renversement de vélo",
    "Vis d’interférence",
    "Maladie amniotique",
    "Fracture prothétique",
    "Pied paralytique",
    "Arthrodèse sous-talienne",
    "Arthrodèse calcanéo-cuboidienne",
    "Cotyle cimenté",
    "Ligamentoplastie du LCA",
    "Thrombose de FAV",
    "Peau menacée",
    "Souffrance cutanée",
    "Ostéotomie de relèvement",
    "Dermatose bulleuse",
    "HBP",
    "E. coli",
    "Masquelet",
    "Reconstruction de poulie A2",
    "Reconstruction de poulie",
    "Bon état général",
    "Syndrome de Noble",
    "Détresse respiratoire aiguë",
    "Pneumonie",
    "Entorse du LCL",
    "Ligamentoplastie du LCL",
    "Demi-tendineux",
    "Kenneth Jones (KJ)",
    "VARFI",
    "Sciatalgie",
    "Fracture Galeazzi",
    "Plaie cervicale",
    "Ressaut rotatoire",
    "Amylose",
    "Lésion labrale",
    "Subluxation de l’épaule",
    "Anti-inflammatoire",
    "Immunosuppresseur",
    "Épine calcanéenne",
    "Aponévrosite plantaire",
    "Désarticulation de l’épaule",
    "Maladie de Verneuil",
    "Dermatose inflammatoire",
    "Éclatement de la tête humérale",
    "Conflit fémoro-acétabulaire",
    "PCI",
    "Fléchisseur radial du carpe",
    "Fléchisseurs superficiels",
    "Régularisation méniscale",
    "Dégénérescence mucoïde du LCA",
    "Résection partielle du LCA",
    "Genou dégénératif",
    "Fracture de l’épicondyle latéral",
    "Maladie de Madelung",
    "Arthrodèse radio-ulnaire distale",
    "CI",
    "Luxation de la cheville fermée",
    "PAPE",
    "Amputation de Lisfranc",
    "Laprade",
    "Greffon quadricipital",
    "Tableau de bord",
    "Tiroir postérieur",
    "Avalement de la TTA",
    "Reverse pivot shift",
    "Hyperrotation externe",
    "Reconstruction du plan latéral",
    "Arrière-pied varus",
    "Ostéotomie calcanéum",
    "Chute de cheval",
    "Triangle de Scarpa",
    "Tumorectomie",
    "Allogreffe structurelle",
    "Anti",
    "Burch-Schneider",
    "Greffe morcelée impactée",
    "Allogreffe massive",
    "Anneau de soutien",
    "Lésion de Bankart",
    "SLAP lésion",
    "Maladie de Charcot-Marie-Tooth",
    "Antiagrégant",
    "Morceau de verre",
    "Fracture bilatérale de l’humérus",
    "Fracture de la base du 1ᵉʳ métacarpe",
    "Asymétrique",
    "Fibula vascularisée",
    "Fracture de la pointe de la rotule",
    "Névralgie",
    "Réparation nerveuse",
    "Névrome",
    "Greffon quadricipital",
    "Mini open",
    "Allergie aux bêta-lactamines",
    "Néo du col utérin",
    "Curiethérapie",
    "Hémosidérine",
    "Fracture céphalo-tubérositaire de l’humérus",
    "Prothèse inversée de l’épaule",
    "Ostéopétrose",
    "Valvulopathie",
    "Remplacement valvulaire cardiaque",
    "Sintrom",
    "Insuffisance veineuse chronique",
    "Rupture négligée du tendon extenseur",
    "Réanimation du tendon",
    "Perte de conscience",
    "Ulcération cutanée chronique",
    "Dermatite chronique",
    "Kyste osseux essentiel",
    "Échographie des parties molles",
    "Trottinette",
    "Luxation talo-crurale",
    "Raideur du poignet",
    "Myofibrosarcome",
    "Reconstruction du plan interne",
    "Arthrolyse MP",
    "Arthrolyse IPP",
    "Kyste hydatique centromédullaire du fémur",
    "Kyste hydatique de la diaphyse fémorale",
    "Manchette commissurale",
    "Pseudarthrose du col fémoral",
    "Stade",
    "Parker 9",
    "Classification de Sandhu",
    "Abcès du psoas",
    "Calcanéoplastie",
    "Peignage",
    "AVC ischémique",
    "Ostéonécrose post-radique",
    "Technique de Versailles",
    "Montage en peigne",
    "Pseudoarthrose septique",
    "Pseudoarthrose",
    "Rhumatisme",
    "Arrachement de l’épine iliaque",
    "Arrachement de l’épine iliaque antéro-inférieure",
    "Plaque de calcanéum",
    "Face latérale du bras",
    "Mobile",
    "Renversement de moto",
    "Ilizarov",
    "Fracture des métacarpes",
    "Ictère",
    "Dilatation des voies biliaires",
    "Pathologie biliaire",
    "Écoulement",
    "Séquestrectomie",
    "Angiocholite",
    "Fracture-luxation ouverte du poignet",
    "Instabilité scapholunaire",
    "Capsulodèse",
    "Cancer du testicule",
    "Ostéotomie de SCARF",
    "Adrénoleucodystrophie",
    "Ténotomie des adducteurs de la hanche",
    "Ténotomie des ischio-jambiers",
    "Instabilité radio-ulnaire distale",
    "Ligamentoplastie de Adams",
    "Broche radio-ulnaire distale",
    "Déformation de Madelung",
    "Tumeur maligne de gaines nerveuses",
    "VIH",
    "Reprise ménisque",
    "Caillot de fibrine",
    "Sarcome phyllode",
    "Traumatisme nerveux périphérique",
    "Pipkin 2",
    "Ostéotomie subtrochantérienne de raccourcissement",
    "PTH sur dysplasie",
    "Ostéotomie d’Akin",
    "Ostéotomie du radius distal",
    "Ostéotomie de raccourcissement de l’ulna",
    "Greffe structurale"
];
