export const SURGEONS_LIST = [
    'Pr. YACOUBI Hicham',
    'Pr. NAJIB AbdelJaouad',
    'Pr. TEBBAA EL HASSALI Achraf',
    'Dr. EL HAICHOUR Ilyesse',
    'Dr. LAMZIRA Mohammed',
    'Dr. BEN SALAH Samir',
    'Dr. DARRAZ Sohayb',
    'Dr. BENABDELLAH ayman',
    'Dr. KHATAB zakaria',
    'Dr. ALSOUDI Issa',
    'Dr. BENALIA kamal',
    'Dr. SEFTI anas',
    'Dr. HAWACHE Hicham',
    'Dr. EL FARHAOUI amine',
    'Dr. BATOU Yassin',
    'Dr. BARZOUQ abdellilah',
    'Dr. SALMI hatim',
    'Dr. MBAINANDARA debonheur',
    'Dr. MARGOUM hamza',
    'Dr. RIFAAI Sami',
    'Dr. TARICHT anas',
    'Dr. ELMAZGALDI said',
    'Dr. SEBBAR Abdessabour',
    'Dr. ZERYOUH brahim',
    'Dr. LAABID ahmed',
    'Dr. NASSIRI omar',
    'Dr. BOULAICH noaim',
    'Dr. LAZAAR houssam',
    'Dr. DAOUDI houcine',
    'Dr. HILALI khalid',
    'Dr. HALY Alae-eddine',
    'Dr. BELFADIL reda',
    'Dr. KHERBACH achraf',
    'Dr. ATIA Alae',
    'Dr. CHALHE Ossama'
];
